# -*- coding: utf-8 -*-
"""条目清单——本仓唯一的数据源，README 与 index.tsv 都由它生成。

每条十个字段：首发日期、最后更新、标题、出品方、体裁、出品方类型、主题、标签、
出处地址、原件键名（连到 fetched.tsv，记录本仓哪天取过原件）。
**不写评价，不写解读**——本仓只做收集、打标签、按发布时间排序。

四根轴互相独立，各答一个问题：体裁问材料是什么形态（六选一，互斥），出品方类型
问谁出的（八选一，互斥），主题问什么在被重构（七个区，可多挂），标签是横切主题的
检索词（英文正名配中文别名，条目只存英文正名，中文由 TAGS 带出）。

**每一轴的判据写在 README.md 的「怎么分类」一节，那里是唯一出处，此处不复述。**
加条目前先读那一节；判据要改也改那里，改完跑 build.py 重新生成。

日期与出品方的填法同样见 README 清单下方的三段说明：首发取原文第一次出现的日子，
最后更新默认 `-` 只填实际采集到的，出品方按原文署名机构填、未署机构的写明。
"""

# 四轴的受控词表。判据见 README.md「怎么分类」。
TOPICS = ["界面与接入", "应用内部", "构造方式", "安全与攻防", "运行与问责",
          "协议与生态", "商业与组织"]
GENRES = ["论文", "规范", "文档", "清单", "报告", "文章"]
ORG_KINDS = ["学界", "厂商", "产学合作", "标准组织", "分析机构", "投资机构",
             "社区与非营利", "个人"]

# 标签的受控词表：(英文正名, 中文别名)。有中文术语的都配上，两种语言都搜得到；
# MCP/A2A/ACP 是协议专名，中文里也这么叫，没有别名，写 None。
# **条目的 tags 只写英文正名**，中文别名由 build.py 按这张表带出——不在条目里各写一遍，
# 否则迟早有人只写一半，同一个概念在清单里就有两套写法。
# 体裁/出品方类型/主题三列仍只用中文：那是本仓自己划的分区，不是原文的词。
TAGS = [
    ("MCP", None), ("A2A", None), ("ACP", None),
    ("registry", "注册表"),
    ("tool-interface", "工具接口"),
    ("payments", "支付"),
    ("context-engineering", "上下文工程"),
    ("ontology", "本体"),
    ("RAG", "检索增强"),
    ("skills", "技能"),
    ("memory", "记忆"),
    ("sandbox", "沙箱"),
    ("observability", "可观测"),
    ("computer-use", "计算机操作"),
    ("decision-model", "决策模型"),
    ("orchestration", "编排"),
    ("authorization", "身份与授权"),
    ("regulation", "法规"),
    ("risk-framework", "风险框架"),
    ("benchmark", "基准评测"),
    ("empirical-study", "实证测量"),
    ("survey", "综述"),
    ("curated-list", "资源清单"),
    ("pricing", "定价"),
    ("headless", "无头化"),
    ("buy-vs-build", "买还是自建"),
    ("market-data", "市场数据"),
]

# 发布日期, 标题, 出品方, 体裁, 出品方类型, [主题], [标签], 出处, 原件键名（对应 fetched.tsv 的名称列）
ITEMS = [
    ("2024-09-01", "2026-09-04", "llms.txt: helping language models use websites",
     "Answer.AI",
     "规范", "厂商", ["界面与接入", "协议与生态"],
     ["context-engineering"],
     "https://github.com/AnswerDotAI/llms-txt",
     "standard-llms-txt"),
    ("2025-04-28", "2026-08-11", "NLWeb: reference implementation for a natural language interface to websites",
     "NLWeb project",
     "文档", "厂商", ["界面与接入"],
     ["tool-interface"],
     "https://github.com/nlweb-ai/NLWeb",
     "vendor-nlweb"),
    ("2025-04-01", "2026-09-20", "Agent Development Kit: an open-source, code-first Python toolkit for building agents",
     "Google",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/google/adk-python",
     "vendor-google-adk"),
    ("2025-05-14", "2026-09-18", "Strands Agents: build an agent harness and control it end-to-end",
     "Amazon Web Services",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/strands-agents/harness-sdk",
     "vendor-strands-agents"),
    ("2023-05-23", "2026-09-20", "AI SDK: the AI toolkit for TypeScript",
     "Vercel",
     "文档", "厂商", ["构造方式"],
     ["tool-interface", "orchestration"],
     "https://github.com/vercel/ai",
     "vendor-vercel-ai-sdk"),
    ("2024-08-06", "2026-09-20", "Mastra: the modern TypeScript framework for AI agents",
     "Mastra",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/mastra-ai/mastra",
     "vendor-mastra"),
    ("2023-03-04", "2026-09-19", "E2B: open-source secure environment with real-world tools for AI agents",
     "E2B",
     "文档", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox"],
     "https://github.com/e2b-dev/E2B",
     "vendor-e2b"),
    ("2024-02-06", "2026-07-24", "Daytona: secure and elastic infrastructure for running AI-generated code",
     "Daytona",
     "文档", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox"],
     "https://github.com/daytonaio/daytona",
     "vendor-daytona"),
    ("2023-12-18", "-", "ISO/IEC 42001:2023 — Information technology, Artificial intelligence, Management system",
     "ISO/IEC",
     "规范", "标准组织", ["运行与问责"],
     ["risk-framework", "regulation"],
     "https://www.iso.org/standard/42001",
     None),
    ("2025-05-30", "2026-06-17", "AP2: Agent Payments Protocol — building a secure and interoperable future for AI-driven payments",
     "Google",
     "规范", "厂商", ["协议与生态", "商业与组织"],
     ["payments"],
     "https://github.com/google-agentic-commerce/AP2",
     "standard-google-ap2"),
    ("2026-04-02", "2026-09-18", "x402: a payments protocol for the internet, built on HTTP",
     "Coinbase",
     "规范", "厂商", ["协议与生态"],
     ["payments"],
     "https://github.com/coinbase/x402",
     "standard-coinbase-x402"),
    ("2023-06-20", "2026-09-19", "Mem0: the memory layer for AI agents",
     "Mem0",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/mem0ai/mem0",
     "vendor-mem0"),
    ("2023-10-11", "2026-09-10", "Letta: platform for stateful agents with advanced memory",
     "Letta",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/letta-ai/letta",
     "vendor-letta"),
    ("2023-04-29", "2026-09-18", "Zep: memory for AI agents",
     "Zep",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/getzep/zep",
     "vendor-zep"),
    ("2017-08-07", "2026-09-02", "SPIFFE: the Secure Production Identity Framework for Everyone",
     "SPIFFE (CNCF)",
     "规范", "标准组织", ["安全与攻防", "运行与问责"],
     ["authorization"],
     "https://github.com/spiffe/spiffe",
     "standard-spiffe"),
    ("2021-04-20", "2026-09-10", "pgvector: open-source vector similarity search for Postgres",
     "pgvector",
     "文档", "社区与非营利", ["应用内部"],
     ["RAG"],
     "https://github.com/pgvector/pgvector",
     "vendor-pgvector"),
    ("2022-10-05", "2026-09-18", "Chroma: search infrastructure for AI",
     "Chroma",
     "文档", "厂商", ["应用内部"],
     ["RAG"],
     "https://github.com/chroma-core/chroma",
     "vendor-chroma"),
    ("2024-11-18", "2026-04-29", "AgentKit: build multi-agent networks in TypeScript",
     "Inngest",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/inngest/agent-kit",
     "vendor-inngest-agentkit"),
    ("2025-09-28", "-", "State of AI-assisted Software Development 2025",
     "DORA (Google Cloud)",
     "报告", "厂商", ["商业与组织"],
     ["empirical-study", "market-data"],
     "https://dora.dev/research/2025/dora-report/",
     "analyst-dora-2025"),
    ("2023-07-13", "-", "生成式人工智能服务管理暂行办法",
     "国家互联网信息办公室等七部门",
     "规范", "标准组织", ["运行与问责"],
     ["regulation"],
     "https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm",
     "standard-cac-genai-measures"),
    ("2025-08-19", "2026-09-10", "AGENTS.md: a simple, open format for guiding coding agents",
     "AGENTS.md project",
     "规范", "标准组织", ["构造方式", "协议与生态"],
     ["skills"],
     "https://github.com/agentsmd/agents.md",
     "standard-agents-md"),
    ("2023-10-04", "2026-09-18", "SWE-bench: can language models resolve real-world GitHub issues?",
     "Princeton University",
     "文档", "学界", ["构造方式"],
     ["benchmark"],
     "https://github.com/SWE-bench/SWE-bench",
     "bench-swe-bench"),
    ("2024-06-06", "2026-03-18", "tau-bench: code and data for Tau-Bench",
     "Sierra",
     "文档", "厂商", ["构造方式"],
     ["benchmark", "tool-interface"],
     "https://github.com/sierra-research/tau-bench",
     "bench-tau-bench"),
    ("2023-05-19", "2026-04-13", "Gorilla: training and evaluating LLMs for function calls (Berkeley Function Calling Leaderboard)",
     "UC Berkeley",
     "文档", "学界", ["构造方式"],
     ["benchmark", "tool-interface"],
     "https://github.com/ShishirPatil/gorilla",
     "bench-gorilla-bfcl"),
    ("2025-01-17", "2026-07-11", "Terminal-Bench: a benchmark for LLMs on complicated tasks in the terminal",
     "Harbor",
     "文档", "社区与非营利", ["构造方式", "界面与接入"],
     ["benchmark"],
     "https://github.com/harbor-framework/terminal-bench-1",
     "bench-terminal-bench"),
    ("2023-11-21", "-", "GAIA: a benchmark for General AI Assistants",
     "FAIR Meta, Hugging Face, AutoGPT",
     "论文", "厂商", ["构造方式"],
     ["benchmark"],
     "https://arxiv.org/abs/2311.12983",
     "academic-2311.12983-gaia"),
    ("2024-06-20", "-", "Semantic conventions for generative AI systems",
     "OpenTelemetry",
     "规范", "标准组织", ["运行与问责"],
     ["observability"],
     "https://opentelemetry.io/docs/specs/semconv/gen-ai/",
     "standard-otel-genai-semconv"),
    ("2023-05-18", "2026-09-19", "Langfuse: open source agent evals and observability",
     "Langfuse",
     "文档", "厂商", ["运行与问责"],
     ["observability"],
     "https://github.com/langfuse/langfuse",
     "vendor-langfuse"),
    ("2022-11-09", "2026-09-19", "Phoenix: AI observability and evaluation",
     "Arize AI",
     "文档", "厂商", ["运行与问责"],
     ["observability"],
     "https://github.com/Arize-ai/phoenix",
     "vendor-arize-phoenix"),
    ("2025-03-21", "2026-09-18", "Playwright MCP server",
     "Microsoft",
     "文档", "厂商", ["界面与接入"],
     ["MCP", "computer-use"],
     "https://github.com/microsoft/playwright-mcp",
     "vendor-playwright-mcp"),
    ("2024-12-05", "2026-07-20", "Browserbase MCP server: allow LLMs to control a browser",
     "Browserbase",
     "文档", "厂商", ["界面与接入"],
     ["MCP", "computer-use"],
     "https://github.com/browserbase/mcp-server-browserbase",
     "vendor-browserbase-mcp"),
    ("2025-11-21", "-", "Computer use tool",
     "Anthropic",
     "文档", "厂商", ["界面与接入"],
     ["computer-use", "tool-interface"],
     "https://platform.claude.com/docs/en/agents-and-tools/tool-use/computer-use-tool",
     "vendor-anthropic-computer-use"),
    ("2025-12-16", "2026-08-09", "Agent Skills: specification and documentation",
     "Agent Skills project",
     "规范", "标准组织", ["构造方式", "协议与生态"],
     ["skills"],
     "https://github.com/agentskills/agentskills",
     "standard-agent-skills-spec"),
    ("2025-10-16", "-", "Equipping agents for the real world with Agent Skills",
     "Anthropic",
     "文章", "厂商", ["构造方式"],
     ["skills", "context-engineering"],
     "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",
     "vendor-anthropic-agent-skills-blog"),
    ("2025-09-22", "2026-09-10", "anthropics/skills: public repository for Agent Skills",
     "Anthropic",
     "文档", "厂商", ["构造方式"],
     ["skills"],
     "https://github.com/anthropics/skills",
     "vendor-anthropic-skills-repo"),
    ("2024-12-05", "2026-08-25", "smolagents: a barebones library for agents that think in code",
     "Hugging Face",
     "文档", "厂商", ["构造方式"],
     ["orchestration", "tool-interface"],
     "https://github.com/huggingface/smolagents",
     "vendor-huggingface-smolagents"),
    ("2022-10-17", "2026-09-20", "LangChain: the agent engineering platform",
     "LangChain",
     "文档", "厂商", ["构造方式"],
     ["tool-interface", "orchestration"],
     "https://github.com/langchain-ai/langchain",
     "vendor-langchain"),
    ("2023-08-09", "2026-09-20", "LangGraph: build resilient agents",
     "LangChain",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/langchain-ai/langgraph",
     "vendor-langgraph"),
    ("2022-11-02", "2026-09-19", "LlamaIndex: the document processing platform for AI",
     "LlamaIndex",
     "文档", "厂商", ["应用内部"],
     ["RAG", "context-engineering"],
     "https://github.com/run-llama/llama_index",
     "vendor-llamaindex"),
    ("2023-10-27", "2026-09-20", "CrewAI: framework for orchestrating role-playing, autonomous AI agents",
     "CrewAI",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/crewAIInc/crewAI",
     "vendor-crewai"),
    ("2023-08-18", "2026-04-15", "AutoGen: a programming framework for agentic AI",
     "Microsoft",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/microsoft/autogen",
     "vendor-microsoft-autogen"),
    ("2025-03-11", "2026-09-20", "OpenAI Agents SDK: a lightweight, powerful framework for multi-agent workflows",
     "OpenAI",
     "文档", "厂商", ["构造方式"],
     ["orchestration", "tool-interface"],
     "https://github.com/openai/openai-agents-python",
     "vendor-openai-agents-sdk"),
    ("2024-06-21", "2026-09-19", "Pydantic AI: how Python does AI",
     "Pydantic",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://github.com/pydantic/pydantic-ai",
     "vendor-pydantic-ai"),
    ("2023-02-27", "2026-09-19", "Semantic Kernel: integrate cutting-edge LLM technology quickly and easily into your apps",
     "Microsoft",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration"],
     "https://github.com/microsoft/semantic-kernel",
     "vendor-microsoft-semantic-kernel"),
    ("2019-11-14", "2026-09-19", "Haystack: open-source AI orchestration framework for building context-engineered, production-ready LLM applications",
     "deepset",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration", "RAG"],
     "https://github.com/deepset-ai/haystack",
     "vendor-deepset-haystack"),
    ("2026-04-28", "-", "Connecting Agents to Decisions",
     "Palantir",
     "文章", "厂商", ["界面与接入", "运行与问责"],
     ["ontology", "orchestration"],
     "https://blog.palantir.com/connecting-agents-to-decisions-277dee8ddb40",
     None),
    ("2026-02-11", "-", "The Ontology system",
     "Palantir",
     "文档", "厂商", ["界面与接入", "应用内部", "运行与问责"],
     ["ontology"],
     "https://www.palantir.com/docs/foundry/architecture-center/ontology-system",
     "vendor-palantir-ontology-system"),
    ("2026-02-01", "-", "LLM-Driven Ontology Construction for Enterprise Knowledge Graphs",
     "Liber AI Research",
     "论文", "社区与非营利", ["应用内部"],
     ["ontology"],
     "https://arxiv.org/abs/2602.01276",
     "academic-2602.01276-llm-ontology-construction"),
    ("2026-02-03", "-", "Ontology-to-tools compilation for executable semantic constraint enforcement in LLM agents",
     "University of Cambridge, CARES Singapore, MIT, CMCL",
     "论文", "产学合作", ["构造方式"],
     ["ontology", "tool-interface"],
     "https://arxiv.org/abs/2602.03439",
     "academic-2602.03439-ontology-to-tools"),
    ("2026-04-01", "2026-06-04", "Ontology-Constrained Neural Reasoning in Enterprise Agentic Systems: A Neurosymbolic Architecture for Domain-Grounded AI Agents",
     "Golden Gate University, Foundation AgenticOS, Novartis",
     "论文", "产学合作", ["构造方式", "应用内部"],
     ["ontology"],
     "https://arxiv.org/abs/2604.00555",
     "academic-2604.00555-ontology-constrained-reasoning"),
    ("2026-04-17", "2026-04-20", "Integrating Graphs, Large Language Models, and Agents: Reasoning and Retrieval",
     "Canadian Institute for Cybersecurity, University of New Brunswick",
     "论文", "学界", ["应用内部"],
     ["ontology", "RAG", "survey"],
     "https://arxiv.org/abs/2604.15951",
     "academic-2604.15951-graphs-llms-agents"),
    ("2025-04-13", "2026-09-20", "Codex: lightweight coding agent that runs in your terminal",
     "OpenAI",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/openai/codex",
     "vendor-openai-codex"),
    ("2025-02-22", "2026-09-20", "Claude Code: an agentic coding tool that lives in your terminal",
     "Anthropic",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/anthropics/claude-code",
     "vendor-anthropic-claude-code"),
    ("2025-04-17", "2026-09-20", "Gemini CLI: an open-source AI agent that brings the power of Gemini directly into your terminal",
     "Google",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/google-gemini/gemini-cli",
     "vendor-google-gemini-cli"),
    ("2025-06-26", "2026-09-20", "Qwen Code: an open-source AI coding agent that lives in your terminal",
     "Alibaba (QwenLM)",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/QwenLM/qwen-code",
     "vendor-qwen-code"),
    ("2023-04-12", "2026-09-20", "Dify: build agentic workflows and RAG pipelines with rich AI model and tool support",
     "LangGenius",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration", "RAG", "context-engineering"],
     "https://github.com/langgenius/dify",
     "vendor-langgenius-dify"),
    ("2025-01-19", "2026-01-27", "UI-TARS: pioneering automated GUI interaction with native agents",
     "ByteDance",
     "文档", "厂商", ["界面与接入"],
     ["tool-interface"],
     "https://github.com/bytedance/UI-TARS",
     "vendor-bytedance-ui-tars"),
    ("2026-08-13", "2026-09-17", "DeepSeek Harness: everything is a plugin",
     "DeepSeek AI",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/deepseek-ai/deepseek-harness",
     "vendor-deepseek-harness"),
    ("2026-08-17", "2026-08-18", "Security Assessment of DeepSeek Harness with A.I.G: Evaluating Resistance to Indirect Prompt Injection",
     "Tencent Zhuque Lab",
     "论文", "厂商", ["安全与攻防", "构造方式"],
     ["tool-interface", "empirical-study"],
     "https://arxiv.org/abs/2608.16393",
     "academic-2608.16393-deepseek-harness-security"),
    ("2026-01-03", "2026-06-22", "MCP-SandboxScan: WASM-based Secure Execution and Runtime Analysis for MCP Tools",
     "University of Glasgow, Aarhus University",
     "论文", "学界", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2601.01241",
     "academic-2601.01241-mcp-sandboxscan"),
    ("2026-01-08", "-", "Internal Representations as Indicators of Hallucinations in Agent Tool Selection",
     "Amazon",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.05214",
     "academic-2601.05214-tool-selection-hallucination"),
    ("2026-01-12", "-", "MCP-ITP: An Automated Framework for Implicit Tool Poisoning in MCP",
     "University of Science and Technology of China",
     "论文", "学界", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2601.07395",
     "academic-2601.07395-mcp-itp-tool-poisoning"),
    ("2026-01-12", "-", "Towards Verifiably Safe Tool Use for LLM Agents",
     "Georgia Institute of Technology, Carnegie Mellon University",
     "论文", "学界", ["安全与攻防", "构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.08012",
     "academic-2601.08012-verifiably-safe-tool-use"),
    ("2026-01-13", "2026-04-19", "ACE-Router: Generalizing History-Aware Routing from MCP Tools to the Agent Web",
     "Zhejiang University, Shanghai Jiao Tong University, Huawei Technologies, Sun Yat-sen University, Nanyang Technological University, Hangzhou Dianzi University",
     "论文", "产学合作", ["协议与生态", "构造方式"],
     ["MCP", "tool-interface"],
     "https://arxiv.org/abs/2601.08276",
     "academic-2601.08276-ace-router"),
    ("2026-01-14", "-", "Beyond Rule-Based Workflows: An Information-Flow-Orchestrated Multi-Agents Paradigm via Agent-to-Agent Communication from CORAL",
     "Coral Protocol, Brunel University of London, University of Luxembourg, University of Hull, National University of Computer and Emerging Sciences",
     "论文", "产学合作", ["构造方式", "协议与生态"],
     ["orchestration"],
     "https://arxiv.org/abs/2601.09883",
     "academic-2601.09883-information-flow-orchestration"),
    ("2026-01-15", "-", "Structure and Diversity Aware Context Bubble Construction for Enterprise Retrieval Augmented Systems",
     "Bravada Group, Eye Dream Pty Ltd",
     "论文", "厂商", ["应用内部"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2601.10681",
     "academic-2601.10681-context-bubble-enterprise-rag"),
    ("2026-01-16", "2026-03-11", "Beyond Max Tokens: Stealthy Resource Amplification via Tool Calling Chains in LLM Agents",
     "Nanyang Technological University, University of Illinois Urbana-Champaign, Hong Kong University of Science and Technology, Shanghai Jiao Tong University",
     "论文", "学界", ["安全与攻防"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.10955",
     "academic-2601.10955-resource-amplification-tool-chains"),
    ("2026-01-16", "2026-01-20", "Institutional AI: Governing LLM Collusion in Multi-Agent Cournot Markets via Public Governance Graphs",
     "DEXAI Icaro Lab, Sapienza University of Rome, Sant'Anna School of Advanced Studies, VU Amsterdam",
     "论文", "产学合作", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.11369",
     "academic-2601.11369-institutional-ai-collusion"),
    ("2026-01-06", "2026-01-22", "Enhancing Model Context Protocol (MCP) with Context-Aware Server Collaboration",
     "University of Chicago",
     "论文", "学界", ["协议与生态"],
     ["MCP", "context-engineering"],
     "https://arxiv.org/abs/2601.11595",
     "academic-2601.11595-context-aware-mcp-collaboration"),
    ("2026-01-20", "-", "The Orchestration of Multi-Agent Systems: Architectures, Protocols, and Enterprise Adoption",
     "Skan AI",
     "论文", "厂商", ["协议与生态", "构造方式"],
     ["orchestration", "survey"],
     "https://arxiv.org/abs/2601.13671",
     "academic-2601.13671-orchestration-multi-agent-systems"),
    ("2026-01-21", "-", "Interoperable Architecture for Digital Identity Delegation for AI Agents with Blockchain Integration",
     "Universidad de Los Andes",
     "论文", "学界", ["安全与攻防"],
     ["authorization"],
     "https://arxiv.org/abs/2601.14982",
     "academic-2601.14982-digital-identity-delegation"),
    ("2026-01-21", "-", "Securing LLM-as-a-Service for Small Businesses: An Industry Case Study of a Distributed Chatbot Deployment Platform",
     "RMIT University",
     "论文", "学界", ["安全与攻防", "运行与问责"],
     ["empirical-study"],
     "https://arxiv.org/abs/2601.15528",
     "academic-2601.15528-securing-llmaas-small-business"),
    ("2026-01-22", "2026-05-17", "Agentic AI Governance and Lifecycle Management in Healthcare",
     "University of the Cumberlands",
     "论文", "学界", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.15630",
     "academic-2601.15630-agentic-governance-healthcare"),
    ("2026-01-24", "-", "Towards a Declarative Agentic Layer for Intelligent Agents in MCP-Based Server Ecosystems",
     "Universidad de Granada",
     "论文", "学界", ["构造方式", "协议与生态"],
     ["MCP", "orchestration"],
     "https://arxiv.org/abs/2601.17435",
     "academic-2601.17435-declarative-agentic-layer"),
    ("2026-01-24", "-", "Breaking the Protocol: Security Analysis of the Model Context Protocol Specification and Prompt Injection Vulnerabilities in Tool-Integrated LLM Agents",
     "No affiliation stated (Narek Maloyan, Dmitry Namiot)",
     "论文", "个人", ["安全与攻防", "协议与生态"],
     ["MCP"],
     "https://arxiv.org/abs/2601.17549",
     "academic-2601.17549-breaking-the-protocol-mcp"),
    ("2026-01-25", "-", "Faramesh: A Protocol-Agnostic Execution Control Plane for Autonomous Agent Systems",
     "The Faramesh Labs",
     "论文", "厂商", ["构造方式", "运行与问责"],
     ["orchestration"],
     "https://arxiv.org/abs/2601.17744",
     "academic-2601.17744-faramesh-control-plane"),
    ("2026-01-29", "-", "Delegation Without Living Governance",
     "AiSuNe Foundation",
     "论文", "社区与非营利", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.21226",
     "academic-2601.21226-delegation-without-living-governance"),
    ("2026-01-30", "2026-05-18", "Whispers of Wealth: Red-Teaming Google's Agent Payments Protocol via Prompt Injection",
     "University of Georgia",
     "论文", "学界", ["安全与攻防", "协议与生态"],
     ["payments"],
     "https://arxiv.org/abs/2601.22569",
     "academic-2601.22569-red-teaming-ap2"),
    ("2026-01-30", "-", "TessPay: Verify-then-Pay Infrastructure for Trusted Agentic Commerce",
     "University of Oxford, Indian Institute of Technology Delhi, Tesseris.org",
     "论文", "产学合作", ["协议与生态", "商业与组织"],
     ["payments"],
     "https://arxiv.org/abs/2602.00213",
     "academic-2602.00213-tesspay-verify-then-pay"),
    ("2026-01-31", "-", "Engineering AI Agents for Clinical Workflows: A Case Study in Architecture, MLOps, and Governance",
     "A3Data, CEFET-MG",
     "论文", "产学合作", ["构造方式", "运行与问责"],
     ["empirical-study"],
     "https://arxiv.org/abs/2602.00751",
     "academic-2602.00751-clinical-workflow-agents"),
    ("2026-02-01", "-", "SMCP: Secure Model Context Protocol",
     "Huazhong University of Science and Technology",
     "论文", "学界", ["安全与攻防", "协议与生态"],
     ["MCP"],
     "https://arxiv.org/abs/2602.01129",
     "academic-2602.01129-smcp-secure-mcp"),
    ("2026-02-06", "2026-06-17", "Graphs Don't Stay Secret: Practical Subgraph Reconstruction Attacks on Defended Graph RAG",
     "KAIST, National Security Research Institute",
     "论文", "学界", ["应用内部", "安全与攻防"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2602.06495",
     "academic-2602.06495-subgraph-reconstruction-graphrag"),
    ("2026-04-16", "2026-08-26", "Corpus2Skill: Distilling Enterprise Knowledge into Navigable Agent Skills for QA and RAG",
     "Magellan Technology Research Institute",
     "论文", "厂商", ["应用内部", "构造方式"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2604.14572",
     "academic-2604.14572-corpus2skill"),
    ("2026-05-28", "2026-08-10", "On Effectiveness and Efficiency of Agentic Tool-calling and RL Training",
     "LMU Munich, Munich Center for Machine Learning, University of Illinois Urbana-Champaign, Amazon, University of Sheffield",
     "论文", "产学合作", ["构造方式"],
     ["tool-interface", "benchmark"],
     "https://arxiv.org/abs/2606.00135",
     "academic-2606.00135-agentic-tool-calling-rl"),
    ("2026-09-16", "-", "Characterizing Network Centralization and Observability in the Remote MCP Ecosystem",
     "University of Calgary",
     "论文", "学界", ["协议与生态", "运行与问责"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.19100",
     "academic-2609.19100-remote-mcp-centralization"),
    ("2024-11-30", "2026-09-15", "awesome-mcp-servers: a collection of MCP servers",
     "Frank Fiegel (punkpeye)",
     "清单", "个人", ["协议与生态"],
     ["MCP", "curated-list"],
     "https://github.com/punkpeye/awesome-mcp-servers",
     "community-punkpeye-mcp-servers"),
    ("2026-09-15", "-", "Introducing System One Models & Jev",
     "TypeSafe AI",
     "文章", "厂商", ["构造方式", "应用内部"],
     ["decision-model", "tool-interface"],
     "https://typesafe.ai/blog/introducing-system-one-models-and-jev",
     "vendor-typesafe-jev-announcement"),
    ("2026-09-15", "-", "Introduction — TypeSafe AI (Jev developer documentation)",
     "TypeSafe AI",
     "文档", "厂商", ["构造方式"],
     ["decision-model", "tool-interface"],
     "https://docs.typesafe.ai/introduction",
     "vendor-typesafe-jev-docs"),
    ("2026-09-14", "-", "Salesforce Koa: An Enterprise Language Model for Agentic Tool Use",
     "Salesforce",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2609.15066",
     "academic-2609.15066-salesforce-koa"),
    ("2026-09-14", "-", "Authorization Architectures for Tool-Using AI Agents",
     "Westcliff University, University of the Cumberlands, Delta Air Lines, Georgia Institute of Technology",
     "论文", "产学合作", ["安全与攻防"],
     ["authorization", "survey"],
     "https://arxiv.org/abs/2609.15906",
     "academic-2609.15906-authorization-architectures"),
    ("2026-09-14", "-", "When Tool Calls Succeed but Workflows Fail: Anomalies at the Agent-Tool Boundary",
     "AVIV Group, independent researcher",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2609.15397",
     "academic-2609.15397-tool-calls-succeed-workflows-fail"),
    ("2026-09-13", "-", "A Two-Dimensional Study of the Model Context Protocol: Publication and Adoption",
     "Luxembourg Institute of Science and Technology, University of Luxembourg",
     "论文", "学界", ["协议与生态"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.14721",
     "academic-2609.14721-mcp-publication-adoption"),
    ("2026-09-13", "-", "The Stochastic Deputy: Structural Tenant Isolation for Tool-Using LLM Agents",
     "Fandaqah, Heidelberg University",
     "论文", "产学合作", ["安全与攻防"],
     ["MCP", "authorization"],
     "https://arxiv.org/abs/2609.14780",
     "academic-2609.14780-stochastic-deputy-tenant-isolation"),
    ("2026-09-12", "-", "Same Name, Different Server: A Security Census of Silent Drift in MCP",
     "Texas Tech University",
     "论文", "学界", ["协议与生态", "安全与攻防"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.14119",
     "academic-2609.14119-same-name-different-server"),
    ("2026-09-10", "-", "Is Bash All You Need? An Empirical Study of Tool Interfaces for Enterprise Digital Worker Agents",
     "Microsoft, Carnegie Mellon University",
     "论文", "产学合作", ["构造方式", "界面与接入"],
     ["tool-interface", "benchmark"],
     "https://arxiv.org/abs/2609.11999",
     "academic-2609.11999-is-bash-all-you-need"),
    ("2026-09-05", "-", "Intent Drift at SME Scale: Deployment Practice, Not Model Capability, Determines Agentic Compliance",
     "Hong Kong University of Science and Technology",
     "论文", "学界", ["运行与问责", "应用内部"],
     ["regulation", "empirical-study"],
     "https://arxiv.org/abs/2609.05975",
     "academic-2609.05975-intent-drift-sme"),
    ("2026-08-31", "-", "Delegation Without Trust: An Empirical Gap Analysis of Identity, Authorization, and Runtime",
     "VotalAI",
     "论文", "厂商", ["安全与攻防"],
     ["authorization"],
     "https://arxiv.org/abs/2609.00267",
     "academic-2609.00267-delegation-without-trust"),
    ("2026-08-25", "-", "Hybrid Semantic Tool Discovery for Enterprise MCP Gateway: Architecture and Implementation",
     "PayPal",
     "论文", "厂商", ["协议与生态", "构造方式"],
     ["MCP", "context-engineering", "tool-interface"],
     "https://arxiv.org/abs/2608.23992",
     "academic-2608.23992-semantic-tool-discovery"),
    ("2025-08-22", "2025-10-11", "MCPVerse: An Expansive, Real-World Benchmark for Agentic Tool Use",
     "SenseTime Research",
     "论文", "厂商", ["构造方式"],
     ["MCP", "benchmark"],
     "https://arxiv.org/abs/2508.16260",
     "academic-2508.16260-mcpverse"),
    ("2026-08-22", "-", "From SQL Generation to Tool Selection: A Domain-Oriented Pattern for MCP Servers",
     "No affiliation stated (Bartolomeo Bogliolo)",
     "论文", "个人", ["界面与接入", "构造方式"],
     ["MCP", "tool-interface"],
     "https://arxiv.org/abs/2608.22063",
     "academic-2608.22063-domain-oriented-tooling"),
    ("2026-08-19", "-", "Expanding Headless 360: Turning Enterprise Applications into Enterprise Capabilities",
     "Salesforce",
     "文章", "厂商", ["界面与接入"],
     ["headless"],
     "https://www.salesforce.com/news/stories/expanding-headless-360-enterprise-capabilities/",
     "vendor-salesforce-headless-360"),
    ("2026-07-28", "-", "Model Context Protocol Specification (version 2026-07-28)",
     "Model Context Protocol",
     "规范", "标准组织", ["协议与生态"],
     ["MCP"],
     "https://modelcontextprotocol.io/specification/latest",
     "standard-mcp-spec-index"),
    ("2026-06-30", "-", "Benchmarking the Benchmarks: A Validity Audit of Tool-Calling Evaluation",
     "CoreThink AI, Stanford University",
     "论文", "产学合作", ["构造方式"],
     ["benchmark"],
     "https://arxiv.org/abs/2607.02577",
     "academic-2607.02577-benchmark-validity-audit"),
    ("2026-06-08", "-", "Understanding How Enterprises Adopt the Model Context Protocol for LLM-Driven Software Engineering",
     "City University of Hong Kong, Hong Kong Metropolitan University",
     "论文", "学界", ["协议与生态", "构造方式"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2606.09182",
     "academic-2606.09182-enterprise-mcp-adoption"),
    ("2026-05-28", "2026-05-28", "Awesome Context Engineering (companion repo)",
     "Institute of Computing Technology CAS, et al.",
     "清单", "学界", ["应用内部", "构造方式"],
     ["context-engineering", "curated-list"],
     "https://github.com/Meirtz/Awesome-Context-Engineering",
     "community-context-engineering-readme"),
    ("2026-05-13", "-", "ServiceNow opens its full system of action to every AI Agent in the enterprise (Action Fabric)",
     "ServiceNow",
     "文章", "厂商", ["界面与接入", "运行与问责"],
     ["headless"],
     "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-opens-its-full-system-of-action-to-every-AI-Agent-in-the-enterprise/default.aspx",
     "vendor-servicenow-action-fabric"),
    ("2026-04-29", "2026-05-02", "The Buy-or-Build Decision, Revisited: How Agentic AI Changes the Economics of Enterprise Software",
     "Stuttgart Media University",
     "论文", "学界", ["商业与组织"],
     ["buy-vs-build"],
     "https://arxiv.org/abs/2604.26482",
     "academic-2604.26482-buy-or-build"),
    ("2026-04-26", "-", "Infrastructure for the Agentic Web: Gap Analysis and Architecture from the Agentverse Platform",
     "OpenHub Research",
     "论文", "社区与非营利", ["协议与生态"],
     ["empirical-study", "registry"],
     "https://arxiv.org/abs/2606.20570",
     "academic-2606.20570-agentic-web-infra"),
    ("2026-04", "-", "SAP API Policy v.4.2026a",
     "SAP",
     "规范", "厂商", ["界面与接入", "协议与生态"],
     ["tool-interface"],
     "https://help.sap.com/doc/sap-api-policy/latest/en-US/API_Policy_latest.pdf",
     "vendor-sap-api-policy"),
    ("2026-03-26", "-", "From Logic Monopoly to Social Contract (working paper, not peer reviewed)",
     "NetX Foundation",
     "论文", "社区与非营利", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2603.25100",
     "academic-2603.25100-logic-monopoly"),
    ("2026-03-02", "-", "Good news: AI Will Eat Application Software",
     "a16z",
     "文章", "投资机构", ["商业与组织"],
     ["headless"],
     "https://a16z.com/good-news-ai-will-eat-application-software/",
     "investor-a16z-eat-application-software"),
    ("2026-03", "-", "AI Isn't Going to \"Eat\" Software: Agentic AI Needs the Authoritative Data and Rules Inside Enterprise Apps",
     "IDC",
     "报告", "分析机构", ["商业与组织"],
     ["headless"],
     "https://my.idc.com/getdoc.jsp?containerId=US54377825",
     "analyst-idc-landing"),
    ("2026-02-24", "-", "The Headless Firm: How AI Reshapes Enterprise Boundaries",
     "Mantix (authors declare a conflict of interest)",
     "论文", "厂商", ["界面与接入", "商业与组织"],
     ["headless"],
     "https://arxiv.org/abs/2602.21401",
     "academic-2602.21401-headless-firm"),
    ("2026-05-18", "-", "Going Headless? On the Boundaries of Vertical AI Firms",
     "University of Pittsburgh, Ensi.ai",
     "论文", "产学合作", ["界面与接入", "商业与组织", "运行与问责"],
     ["headless"],
     "https://arxiv.org/abs/2605.17812",
     "academic-2605.17812-going-headless"),
    ("2025-12-09", "-", "2025: The State of Generative AI in the Enterprise (survey of 495 respondents)",
     "Menlo Ventures",
     "报告", "投资机构", ["商业与组织"],
     ["market-data"],
     "https://menlovc.com/perspective/2025-the-state-of-generative-ai-in-the-enterprise/",
     "investor-menlo-state-of-genai"),
    ("2025-12-09", "-", "OWASP Top 10 for Agentic Applications for 2026",
     "OWASP GenAI Security Project",
     "规范", "社区与非营利", ["安全与攻防"],
     ["risk-framework"],
     "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
     "standard-owasp-top10-agentic"),
    ("2025-11-25", "-", "Securing the Model Context Protocol (MCP): Risks, Controls, and Governance",
     "Vanta, MintMCP, Darktrace",
     "论文", "厂商", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2511.20920",
     "academic-2511.20920-securing-mcp"),
    ("2025-11-05", "-", "Technology Radar: Model Context Protocol (MCP) assessed as Trial",
     "ThoughtWorks",
     "报告", "分析机构", ["协议与生态"],
     ["MCP"],
     "https://www.thoughtworks.com/radar/platforms/model-context-protocol-mcp",
     "analyst-thoughtworks-radar-mcp"),
    ("2025-08-05", "2025-10-20", "Evolution of AI Agent Registry Solutions: Centralized, Enterprise, and Distributed Approaches",
     "MIT, Cisco, Cleveland State University, et al.",
     "论文", "产学合作", ["协议与生态"],
     ["registry", "survey"],
     "https://arxiv.org/abs/2508.03095",
     "academic-2508.03095-agent-registries"),
    ("2025-09-11", "-", "Writing effective tools for agents — with agents",
     "Anthropic",
     "文章", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://www.anthropic.com/engineering/writing-tools-for-agents",
     "toolcraft-anthropic-writing-tools"),
    ("2025-09-01", "-", "An Economy of AI Agents (NBER handbook chapter)",
     "Johns Hopkins University, MIT",
     "论文", "学界", ["商业与组织"],
     ["survey"],
     "https://arxiv.org/abs/2509.01063",
     "academic-2509.01063-economy-of-ai-agents"),
    ("2025-07-17", "2025-07-21", "A Survey of Context Engineering for Large Language Models",
     "Institute of Computing Technology CAS, Peking University, Tsinghua University, et al.",
     "论文", "学界", ["应用内部"],
     ["context-engineering", "survey"],
     "https://arxiv.org/abs/2507.13334",
     "academic-2507.13334-context-engineering-survey"),
    ("2025-04-11", "2025-05-02", "Enterprise-Grade Security for the Model Context Protocol (MCP)",
     "Amazon Web Services, Intuit",
     "论文", "厂商", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2504.08623",
     "academic-2504.08623-enterprise-mcp-security"),
    ("2025-05-06", "-", "From Glue-Code to Protocols: A Critical Analysis of A2A and MCP Integration",
     "Kennesaw State University",
     "论文", "学界", ["协议与生态"],
     ["MCP", "A2A"],
     "https://arxiv.org/abs/2505.03864",
     "academic-2505.03864-a2a-mcp-integration"),
    ("2025-02-05", "2026-09-16", "MCP Registry: a community driven registry service for Model Context Protocol servers",
     "Model Context Protocol",
     "文档", "标准组织", ["协议与生态"],
     ["MCP", "registry"],
     "https://github.com/modelcontextprotocol/registry",
     "standard-mcp-registry-design-principles"),
    ("2025-03-25", "2026-09-16", "A2A Protocol",
     "Linux Foundation",
     "文档", "标准组织", ["协议与生态"],
     ["A2A"],
     "https://a2a-protocol.org/latest/",
     "standard-a2a-protocol-home"),
    ("2025-08-25", "-", "ACP Joins Forces with A2A Under the Linux Foundation",
     "BeeAI project (led by IBM Research)",
     "文章", "标准组织", ["协议与生态"],
     ["ACP", "A2A"],
     "https://github.com/orgs/i-am-bee/discussions/5",
     "announce-acp-joins-a2a"),
    ("2025-05-01", "-", "Extend Atlassian into any AI assistant using MCP",
     "Atlassian",
     "文档", "厂商", ["界面与接入", "运行与问责"],
     ["MCP"],
     "https://www.atlassian.com/platform/remote-mcp-server",
     "vendor-atlassian-remote-mcp"),
    ("2025-02-12", "-", "Salesforce Agentforce Pricing (per-conversation)",
     "Salesforce",
     "文档", "厂商", ["商业与组织"],
     ["pricing"],
     "https://www.salesforce.com/agentforce/pricing/",
     "vendor-salesforce-agentforce-pricing"),
    ("2025-05-22", "-", "Fin AI Agent Pricing (per-outcome)",
     "Intercom",
     "文档", "厂商", ["商业与组织"],
     ["pricing"],
     "https://fin.ai/pricing",
     "vendor-intercom-fin-pricing"),
    ("2023-11-06", "-", "Function calling",
     "OpenAI",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://platform.openai.com/docs/guides/function-calling",
     "toolcraft-openai-function-calling"),
    ("2021-08-12", "-", "AI Risk Management Framework",
     "NIST",
     "规范", "标准组织", ["运行与问责"],
     ["risk-framework"],
     "https://www.nist.gov/itl/ai-risk-management-framework",
     "standard-nist-ai-rmf"),
    ("2024-08-10", "-", "Implementation Timeline — EU Artificial Intelligence Act",
     "Future of Life Institute (tracker)",
     "清单", "社区与非营利", ["运行与问责"],
     ["regulation"],
     "https://artificialintelligenceact.eu/implementation-timeline/",
     "community-eu-ai-act-timeline"),
    ("2026-06-03", "-", "The State Of Agentic AI In 2026 (public blog post)",
     "Forrester",
     "文章", "分析机构", ["商业与组织"],
     ["market-data"],
     "https://www.forrester.com/blogs/the-state-of-agentic-ai-in-2026-companies-are-chasing-few-are-catching/",
     "analyst-forrester-state-of-agentic-ai"),
    ("2026-02-10", "2026-09-12", "awesome-ai-agent-papers: a curated collection of AI agent research papers released in 2026",
     "VoltAgent",
     "清单", "厂商", ["应用内部", "构造方式", "运行与问责"],
     ["curated-list"],
     "https://github.com/VoltAgent/awesome-ai-agent-papers",
     "community-voltagent-agent-papers"),
    ("2025-04-08", "2026-03-03", "awesome-mcp-security",
     "Maciej Pulikowski (Puliczek)",
     "清单", "个人", ["安全与攻防"],
     ["MCP", "curated-list"],
     "https://github.com/Puliczek/awesome-mcp-security",
     "community-puliczek-mcp-security"),
    ("2026-03-14", "2026-03-14", "Awesome MCP Security: security scores for 800+ MCP servers",
     "Agentseal",
     "清单", "厂商", ["安全与攻防", "协议与生态"],
     ["MCP", "curated-list"],
     "https://github.com/getagentseal/awesome-mcp-security",
     "community-agentseal-mcp-server-scores"),
    ("2024-07-16", "-", "百炼文档（兼容 OpenAI 接口规范）",
     "阿里云",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://help.aliyun.com/zh/model-studio/",
     "platform-aliyun-bailian"),
    ("2026-09-18", "-", "网络安全标准实践指南——智能体系统开发安全指南（征求意见稿 v1.0-202609）",
     "全国网络安全标准化技术委员会",
     "规范", "标准组织", ["安全与攻防", "界面与接入"],
     ["regulation"],
     "https://www.tc260.org.cn/tc260/tzgg/202609/e5b82ae7aca244d19d36b39575cbb458.shtml",
     "standard-tc260-agent-dev-security-guide"),
]

# 原件不随仓分发的，写明理由。其余默认「可用 fetch.sh 取回本地」。
NO_REDISTRIBUTION = {
    "standard-tc260-agent-dev-security-guide":
        "文件声明「未经秘书处书面授权，不得以任何方式抄袭、翻译任何部分」",
    "analyst-idc-landing": "正文在付费墙后，此处仅落地页元数据",
}
ARXIV_NOTE = ("arXiv 默认许可为 nonexclusive-distrib/1.0——作者授权 arXiv 分发，"
              "**未授权第三方转载**，故本仓不放 PDF 副本")
