# -*- coding: utf-8 -*-
"""条目清单——本仓唯一的数据源，README 与 index.tsv 都由它生成。

每条十一个字段：首发日期、最后更新、标题、出品方、体裁、出品方类型、主题、标签、
出处地址、原件键名（连到 fetched.tsv，记录本仓哪天取过原件）、事实性摘要、收录理由。
摘要概括原文明确陈述的对象、方法或范围；收录理由说明原文内容如何对应本仓范围；两者均不写评价、推测或建议。

四根轴互相独立，各答一个问题：体裁问材料是什么形态（六选一，互斥），出品方类型
问谁出的（八选一，互斥），主题问什么在被重构（七个区，可多挂），标签是横切主题的
检索词（英文正名配中文别名，条目只存英文正名，中文由 TAGS 带出）。

**每一轴的判据写在 policy.py，那里是唯一出处；README 的「怎么分类」由它生成。**
加条目前先读 README 的展示版；判据要改则改 policy.py，改完跑 build.py 重新生成。

日期与出品方的填法同样见 README 清单下方的三段说明：首发取原文第一次出现的日子，
最后更新默认 `-` 只填实际采集到的，出品方按原文署名机构填、未署机构的写明。
"""

from collections import namedtuple

# 四轴的受控词表。判据见 policy.py，展示版见 README.md「怎么分类」。
TOPICS = ["界面与接入", "应用内部", "构造方式", "安全与攻防", "运行与问责",
          "协议与生态", "商业与组织"]
GENRES = ["论文", "规范", "文档", "清单", "报告", "文章"]
ORG_KINDS = ["学界", "厂商", "产学合作", "标准组织", "分析机构", "投资机构",
             "社区与非营利", "个人"]

# 标签的受控词表：(英文正名, 中文别名)。有中文术语的都配上，两种语言都搜得到；
# MCP/A2A/ACP 是协议专名，中文里也这么叫，没有别名，写 None。
# **条目的 tags 只写英文正名**，中文别名由 build.py 按这张表带出——不在条目里各写一遍，
# 否则迟早有人只写一半，同一个概念在清单里就有两套写法。
# 体裁/出品方类型/主题三列仍只用中文：那是本仓自己划的分区，不是原文的词。
TAGS = [
    ("MCP", None), ("A2A", None), ("ACP", None),
    ("registry", "注册表"),
    ("tool-interface", "工具接口"),
    ("payments", "支付"),
    ("context-engineering", "上下文工程"),
    ("ontology", "本体"),
    ("RAG", "检索增强"),
    ("skills", "技能"),
    ("plugins", "插件"),
    ("memory", "记忆"),
    ("sandbox", "沙箱"),
    ("observability", "可观测"),
    ("computer-use", "计算机操作"),
    ("decision-model", "决策模型"),
    ("orchestration", "编排"),
    ("authorization", "身份与授权"),
    ("regulation", "法规"),
    ("risk-framework", "风险框架"),
    ("benchmark", "基准评测"),
    ("empirical-study", "实证测量"),
    ("survey", "综述"),
    ("curated-list", "资源清单"),
    ("pricing", "定价"),
    ("headless", "无头化"),
    ("buy-vs-build", "买还是自建"),
    ("market-data", "市场数据"),
]

# 可辨识的品牌与代表产品/项目，值为「品牌；代表产品/项目」。只在出处明确关联、
# 且能帮助读者认出出品方时填写；未列出的条目不推断关联。
BRAND_CONTEXT = {
    "https://github.com/google/adk-python": "Google AI；Agent Development Kit",
    "https://github.com/strands-agents/harness-sdk": "AWS；Strands Agents",
    "https://github.com/vercel/ai": "Vercel；AI SDK",
    "https://github.com/google-agentic-commerce/AP2": "Google；AP2",
    "https://dora.dev/research/2025/dora-report/": "Google Cloud；DORA",
    "https://github.com/microsoft/playwright-mcp": "Microsoft；Playwright MCP",
    "https://platform.claude.com/docs/en/agents-and-tools/tool-use/computer-use-tool": "Anthropic；Claude computer use",
    "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills": "Anthropic；Claude Agent Skills",
    "https://github.com/anthropics/skills": "Anthropic；Claude Skills",
    "https://github.com/langchain-ai/langchain": "LangChain；LangChain",
    "https://github.com/langchain-ai/langgraph": "LangChain；LangGraph",
    "https://github.com/microsoft/autogen": "Microsoft；AutoGen",
    "https://github.com/openai/openai-agents-python": "OpenAI；Agents SDK",
    "https://github.com/microsoft/semantic-kernel": "Microsoft；Semantic Kernel",
    "https://blog.palantir.com/connecting-agents-to-decisions-277dee8ddb40": "Palantir；AIP",
    "https://www.palantir.com/docs/foundry/architecture-center/ontology-system": "Palantir；Foundry Ontology",
    "https://github.com/openai/codex": "OpenAI；Codex",
    "https://github.com/anthropics/claude-code": "Anthropic；Claude Code",
    "https://github.com/google-gemini/gemini-cli": "Google；Gemini CLI",
    "https://github.com/QwenLM/qwen-code": "Alibaba；Qwen Code",
    "https://github.com/langgenius/dify": "LangGenius；Dify",
    "https://github.com/bytedance/UI-TARS": "ByteDance；UI-TARS",
    "https://github.com/deepseek-ai/deepseek-harness": "DeepSeek；DeepSeek Harness",
    "https://arxiv.org/abs/2609.15066": "Salesforce；Koa",
    "https://www.salesforce.com/news/press-releases/2026/09/15/koa-reasoning-model/": "Salesforce；Koa",
    "https://www.salesforce.com/news/stories/why-we-post-trained-our-own-reasoning-model/": "Salesforce；Koa",
    "https://www.salesforce.com/news/stories/expanding-headless-360-enterprise-capabilities/": "Salesforce；Headless 360",
    "https://www.salesforce.com/agentforce/pricing/": "Salesforce；Agentforce",
    "https://fin.ai/pricing": "Intercom；Fin AI Agent",
    "https://platform.openai.com/docs/guides/function-calling": "OpenAI；Function calling",
    "https://typesafe.ai/blog/introducing-system-one-models-and-jev": "TypeSafe AI；System One / Jev",
    "https://docs.typesafe.ai/introduction": "TypeSafe AI；Jev",
    "https://github.com/zai-org/ZCode": "智谱 AI；GLM",
}

# 条目结构由生成器与校验器共用；ITEMS 仍保持紧凑的元组写法。
Item = namedtuple("Item", "first updated title org genre org_kind topics tags url key summary rationale")

# 发布日期, 标题, 出品方, 体裁, 出品方类型, [主题], [标签], 出处, 原件键名（对应 fetched.tsv 的名称列）, 摘要, 收录理由
ITEMS = [
    ("2024-09-01", "2026-09-04", "llms.txt: helping language models use websites",
     "Answer.AI",
     "规范", "厂商", ["界面与接入", "协议与生态"],
     ["context-engineering"],
     "https://github.com/AnswerDotAI/llms-txt",
     "standard-llms-txt", "提出一种网站侧的 Markdown 文件约定，用于向语言模型介绍网站内容结构、重要页面和访问提示。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-28", "2026-08-11", "NLWeb: reference implementation for a natural language interface to websites",
     "NLWeb project",
     "文档", "厂商", ["界面与接入"],
     ["tool-interface"],
     "https://github.com/nlweb-ai/NLWeb",
     "vendor-nlweb", "提供网站自然语言问答界面，将结构化网站内容转换为供用户和 AI 助手查询的接口，并支持 MCP。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-01", "2026-09-20", "Agent Development Kit: an open-source, code-first Python toolkit for building agents",
     "Google",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/google/adk-python",
     "vendor-google-adk", "Google 的 Python 开发工具包，提供构建、组合和运行智能体所需的模型、工具、工作流与会话能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-05-14", "2026-09-18", "Strands Agents: build an agent harness and control it end-to-end",
     "Amazon Web Services",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/strands-agents/harness-sdk",
     "vendor-strands-agents", "介绍一种以模型调用为中心的智能体开发框架，支持连接模型、工具和多个智能体来构建应用。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-05-23", "2026-09-20", "AI SDK: the AI toolkit for TypeScript",
     "Vercel",
     "文档", "厂商", ["构造方式"],
     ["tool-interface", "orchestration"],
     "https://github.com/vercel/ai",
     "vendor-vercel-ai-sdk", "提供 TypeScript SDK，用统一接口连接生成式模型，并构建文本生成、结构化输出和流式交互应用。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-08-06", "2026-09-20", "Mastra: the modern TypeScript framework for AI agents",
     "Mastra",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/mastra-ai/mastra",
     "vendor-mastra", "TypeScript 智能体开发平台，涵盖工作流、检索增强生成、记忆、评估及应用部署。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-03-04", "2026-09-19", "E2B: open-source secure environment with real-world tools for AI agents",
     "E2B",
     "文档", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox"],
     "https://github.com/e2b-dev/E2B",
     "vendor-e2b", "提供供 AI 智能体运行代码和工具的隔离云端沙箱环境及相关 SDK。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-02-06", "2026-07-24", "Daytona: secure and elastic infrastructure for running AI-generated code",
     "Daytona",
     "文档", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox"],
     "https://github.com/daytonaio/daytona",
     "vendor-daytona", "介绍运行 AI 生成代码的安全执行环境；仓库说明核心开发已迁至私有代码库，公开仓库自 2026 年 6 月起不再更新。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-12-18", "-", "ISO/IEC 42001:2023 — Information technology, Artificial intelligence, Management system",
     "ISO/IEC",
     "规范", "标准组织", ["运行与问责"],
     ["risk-framework", "regulation"],
     "https://www.iso.org/standard/42001",
     None, "", '原文内容呈现题名所示的 AI 管理体系标准涉及 AI 软件运行治理；当前未转述受限正文。，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-05-30", "2026-06-17", "AP2: Agent Payments Protocol — building a secure and interoperable future for AI-driven payments",
     "Google",
     "规范", "厂商", ["协议与生态", "商业与组织"],
     ["payments"],
     "https://github.com/google-agentic-commerce/AP2",
     "standard-google-ap2", "该仓库提供 Agent Payments Protocol 的代码示例与演示，用于展示智能体发起支付时的协议流程。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-02", "2026-09-18", "x402: a payments protocol for the internet, built on HTTP",
     "Coinbase",
     "规范", "厂商", ["协议与生态"],
     ["payments"],
     "https://github.com/coinbase/x402",
     "standard-coinbase-x402", "定义一种基于 HTTP 的互联网支付标准，并提供让网站或服务按请求接收数字货币及法币支付的实现示例。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-06-20", "2026-09-19", "Mem0: the memory layer for AI agents",
     "Mem0",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/mem0ai/mem0",
     "vendor-mem0", "提供面向智能体和生成式 AI 应用的持久记忆组件，用于保存并检索跨会话的用户与任务信息。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-10-11", "2026-09-10", "Letta: platform for stateful agents with advanced memory",
     "Letta",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/letta-ai/letta",
     "vendor-letta", "提供构建有状态智能体的平台与框架，支持持久记忆、运行时状态和面向开发者的代理应用。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-04-29", "2026-09-18", "Zep: memory for AI agents",
     "Zep",
     "文档", "厂商", ["应用内部"],
     ["memory"],
     "https://github.com/getzep/zep",
     "vendor-zep", "收录 Zep Cloud 的 SDK 示例与服务集成代码，展示如何在应用中调用其智能体记忆与上下文能力。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2017-08-07", "2026-09-02", "SPIFFE: the Secure Production Identity Framework for Everyone",
     "SPIFFE (CNCF)",
     "规范", "标准组织", ["安全与攻防", "运行与问责"],
     ["authorization"],
     "https://github.com/spiffe/spiffe",
     "standard-spiffe", "定义服务工作负载的身份标识及相互认证标准，使服务能够以可验证身份建立安全通信。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2021-04-20", "2026-09-10", "pgvector: open-source vector similarity search for Postgres",
     "pgvector",
     "文档", "社区与非营利", ["应用内部"],
     ["RAG"],
     "https://github.com/pgvector/pgvector",
     "vendor-pgvector", "为 PostgreSQL 增加向量数据类型和相似度搜索能力，支持精确及近似近邻索引与多种距离度量。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2022-10-05", "2026-09-18", "Chroma: search infrastructure for AI",
     "Chroma",
     "文档", "厂商", ["应用内部"],
     ["RAG"],
     "https://github.com/chroma-core/chroma",
     "vendor-chroma", "介绍用于 AI 应用的数据基础设施，提供向量、文档和元数据的存储、检索及相关查询接口。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-11-18", "2026-04-29", "AgentKit: build multi-agent networks in TypeScript",
     "Inngest",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/inngest/agent-kit",
     "vendor-inngest-agentkit", "提供 TypeScript 多智能体开发工具，用于定义智能体、任务工具及协作流程。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-09-28", "-", "State of AI-assisted Software Development 2025",
     "DORA (Google Cloud)",
     "报告", "厂商", ["商业与组织"],
     ["empirical-study", "market-data"],
     "https://dora.dev/research/2025/dora-report/",
     "analyst-dora-2025", "DORA 的研究报告讨论 AI 辅助软件开发的使用情况，并呈现其调查结果及与软件交付、组织能力相关的分析。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-07-13", "-", "生成式人工智能服务管理暂行办法",
     "国家互联网信息办公室等七部门",
     "规范", "标准组织", ["运行与问责"],
     ["regulation"],
     "https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm",
     "standard-cac-genai-measures", "规定在中国境内向公众提供生成式人工智能服务时的适用范围、服务提供者义务、数据安全和内容管理要求。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-08-19", "2026-09-10", "AGENTS.md: a simple, open format for guiding coding agents",
     "AGENTS.md project",
     "规范", "标准组织", ["构造方式", "协议与生态"],
     ["skills"],
     "https://github.com/agentsmd/agents.md",
     "standard-agents-md", "定义一个用于向代码智能体提供项目背景和操作约定的开放文件格式，可在代码仓库中放置 AGENTS.md 指南。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-10-04", "2026-09-18", "SWE-bench: can language models resolve real-world GitHub issues?",
     "Princeton University",
     "文档", "学界", ["构造方式"],
     ["benchmark"],
     "https://github.com/SWE-bench/SWE-bench",
     "bench-swe-bench", "以真实 GitHub 问题和对应代码仓库为任务，构成评估语言模型定位问题、修改代码并通过测试能力的基准。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-06-06", "2026-03-18", "tau-bench: code and data for Tau-Bench",
     "Sierra",
     "文档", "厂商", ["构造方式"],
     ["benchmark", "tool-interface"],
     "https://github.com/sierra-research/tau-bench",
     "bench-tau-bench", "通过航空与零售等场景中的工具、用户和环境交互任务，评测智能体在规则约束下完成多轮任务的能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-05-19", "2026-04-13", "Gorilla: training and evaluating LLMs for function calls (Berkeley Function Calling Leaderboard)",
     "UC Berkeley",
     "文档", "学界", ["构造方式"],
     ["benchmark", "tool-interface"],
     "https://github.com/ShishirPatil/gorilla",
     "bench-gorilla-bfcl", "建立函数调用评测基准，覆盖多种参数结构、并行及多轮调用场景，用于测试模型选择和调用 API 的表现。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-01-17", "2026-07-11", "Terminal-Bench: a benchmark for LLMs on complicated tasks in the terminal",
     "Harbor",
     "文档", "社区与非营利", ["构造方式", "界面与接入"],
     ["benchmark"],
     "https://github.com/harbor-framework/terminal-bench-1",
     "bench-terminal-bench", "提供面向终端环境的智能体任务基准，用于评测模型在命令行中操作工具、完成软件工程及系统任务的能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-11-21", "-", "GAIA: a benchmark for General AI Assistants",
     "FAIR Meta, Hugging Face, AutoGPT",
     "论文", "厂商", ["构造方式"],
     ["benchmark"],
     "https://arxiv.org/abs/2311.12983",
     "academic-2311.12983-gaia", "构建通用 AI 助手基准，使用需要推理、多模态理解、网页浏览和工具使用的问题评测系统能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-06-20", "-", "Semantic conventions for generative AI systems",
     "OpenTelemetry",
     "规范", "标准组织", ["运行与问责"],
     ["observability"],
     "https://opentelemetry.io/docs/specs/semconv/gen-ai/",
     "standard-otel-genai-semconv", "定义生成式 AI 系统遥测数据的统一命名约定，涉及模型、请求、生成内容及相关使用指标。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-05-18", "2026-09-19", "Langfuse: open source agent evals and observability",
     "Langfuse",
     "文档", "厂商", ["运行与问责"],
     ["observability"],
     "https://github.com/langfuse/langfuse",
     "vendor-langfuse", "提供开源的 LLM 应用观测与评估平台，用于记录模型调用轨迹、管理提示词并测试应用输出。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2022-11-09", "2026-09-19", "Phoenix: AI observability and evaluation",
     "Arize AI",
     "文档", "厂商", ["运行与问责"],
     ["observability"],
     "https://github.com/Arize-ai/phoenix",
     "vendor-arize-phoenix", "提供面向 LLM 应用的开源观测和评估工具，用于查看调用链路、分析模型行为及执行评测。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-03-21", "2026-09-18", "Playwright MCP server",
     "Microsoft",
     "文档", "厂商", ["界面与接入"],
     ["MCP", "computer-use"],
     "https://github.com/microsoft/playwright-mcp",
     "vendor-playwright-mcp", "将 Playwright 浏览器自动化能力封装为 MCP 工具，使智能体可通过结构化页面信息操作网页。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-12-05", "2026-07-20", "Browserbase MCP server: allow LLMs to control a browser",
     "Browserbase",
     "文档", "厂商", ["界面与接入"],
     ["MCP", "computer-use"],
     "https://github.com/browserbase/mcp-server-browserbase",
     "vendor-browserbase-mcp", "该仓库提供连接 LLM 与 Browserbase 浏览器会话的 MCP 服务器参考实现；仓库已归档，作者说明其不代表当前生产服务。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-11-21", "-", "Computer use tool",
     "Anthropic",
     "文档", "厂商", ["界面与接入"],
     ["computer-use", "tool-interface"],
     "https://platform.claude.com/docs/en/agents-and-tools/tool-use/computer-use-tool",
     "vendor-anthropic-computer-use", "说明如何向 Claude 提供屏幕截图、鼠标和键盘控制能力，使模型能够与桌面环境交互。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-12-16", "2026-08-09", "Agent Skills: specification and documentation",
     "Agent Skills project",
     "规范", "标准组织", ["构造方式", "协议与生态"],
     ["skills"],
     "https://github.com/agentskills/agentskills",
     "standard-agent-skills-spec", "定义 Agent Skills 开放规范，以包含 SKILL.md、脚本和资源的目录为单位，为智能体提供可复用能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-10-16", "-", "Equipping agents for the real world with Agent Skills",
     "Anthropic",
     "文章", "厂商", ["构造方式"],
     ["skills", "context-engineering"],
     "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",
     "vendor-anthropic-agent-skills-blog", "介绍 Anthropic 如何用模块化技能说明、脚本和资源为智能体提供处理现实任务的专门流程。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-09-22", "2026-09-10", "anthropics/skills: public repository for Agent Skills",
     "Anthropic",
     "文档", "厂商", ["构造方式"],
     ["skills"],
     "https://github.com/anthropics/skills",
     "vendor-anthropic-skills-repo", "收录 Anthropic 为 Claude 提供的技能示例，内容包括可重复使用的操作说明、脚本和配套资源。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-12-05", "2026-08-25", "smolagents: a barebones library for agents that think in code",
     "Hugging Face",
     "文档", "厂商", ["构造方式"],
     ["orchestration", "tool-interface"],
     "https://github.com/huggingface/smolagents",
     "vendor-huggingface-smolagents", "提供轻量级 Python 智能体框架，支持用代码生成行动或调用工具来执行任务。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2022-10-17", "2026-09-20", "LangChain: the agent engineering platform",
     "LangChain",
     "文档", "厂商", ["构造方式"],
     ["tool-interface", "orchestration"],
     "https://github.com/langchain-ai/langchain",
     "vendor-langchain", "提供构建 LLM 应用与智能体的开发框架，包含模型、工具、数据连接和运行流程等集成组件。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-08-09", "2026-09-20", "LangGraph: build resilient agents",
     "LangChain",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/langchain-ai/langgraph",
     "vendor-langgraph", "提供有状态智能体编排框架，支持持久化运行状态、检查点、人工介入和长时任务执行。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2022-11-02", "2026-09-19", "LlamaIndex: the document processing platform for AI",
     "LlamaIndex",
     "文档", "厂商", ["应用内部"],
     ["RAG", "context-engineering"],
     "https://github.com/run-llama/llama_index",
     "vendor-llamaindex", "提供用于连接数据与 LLM 应用的框架，支持数据摄取、索引、检索以及基于数据构建智能体工作流。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-10-27", "2026-09-20", "CrewAI: framework for orchestrating role-playing, autonomous AI agents",
     "CrewAI",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/crewAIInc/crewAI",
     "vendor-crewai", "提供以角色、任务和工具组织多个智能体的框架，并支持定义更完整的协作流程。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-08-18", "2026-04-15", "AutoGen: a programming framework for agentic AI",
     "Microsoft",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/microsoft/autogen",
     "vendor-microsoft-autogen", "提供构建多智能体应用的编程框架，包含消息通信、智能体协作和运行时组件。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-03-11", "2026-09-20", "OpenAI Agents SDK: a lightweight, powerful framework for multi-agent workflows",
     "OpenAI",
     "文档", "厂商", ["构造方式"],
     ["orchestration", "tool-interface"],
     "https://github.com/openai/openai-agents-python",
     "vendor-openai-agents-sdk", "提供构建智能体和多智能体工作流的 Python SDK，包含工具调用、交接、护栏、会话及追踪能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-06-21", "2026-09-19", "Pydantic AI: how Python does AI",
     "Pydantic",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://github.com/pydantic/pydantic-ai",
     "vendor-pydantic-ai", "提供以 Python 类型系统为基础的智能体开发框架，支持模型连接、依赖注入、结构化输出和结果校验。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-02-27", "2026-09-19", "Semantic Kernel: integrate cutting-edge LLM technology quickly and easily into your apps",
     "Microsoft",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration"],
     "https://github.com/microsoft/semantic-kernel",
     "vendor-microsoft-semantic-kernel", "提供将生成式模型集成到应用中的开发框架；仓库现说明其后继项目为 Microsoft Agent Framework。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2019-11-14", "2026-09-19", "Haystack: open-source AI orchestration framework for building context-engineered, production-ready LLM applications",
     "deepset",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration", "RAG"],
     "https://github.com/deepset-ai/haystack",
     "vendor-deepset-haystack", "提供构建检索增强生成和智能体应用的开源 Python 框架，以可组合组件和管线组织数据处理与模型调用。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-28", "-", "Connecting Agents to Decisions",
     "Palantir",
     "文章", "厂商", ["界面与接入", "运行与问责"],
     ["ontology", "orchestration"],
     "https://blog.palantir.com/connecting-agents-to-decisions-277dee8ddb40",
     None, "文章介绍 Palantir Ontology 的决策中心架构，将企业数据、业务逻辑、行动及安全策略连接起来以供人员和智能体使用。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-11", "-", "The Ontology system",
     "Palantir",
     "文档", "厂商", ["界面与接入", "应用内部", "运行与问责"],
     ["ontology"],
     "https://www.palantir.com/docs/foundry/architecture-center/ontology-system",
     "vendor-palantir-ontology-system", "说明 Palantir Ontology 如何用对象、属性、链接和行动表示企业中的真实业务实体与操作。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 改变软件内部功能、流程或数据处理的方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-01", "-", "LLM-Driven Ontology Construction for Enterprise Knowledge Graphs",
     "Liber AI Research",
     "论文", "社区与非营利", ["应用内部"],
     ["ontology"],
     "https://arxiv.org/abs/2602.01276",
     "academic-2602.01276-llm-ontology-construction", "提出使用大语言模型生成企业知识图谱本体的流程，以减少领域本体构建中的手工工作。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-03", "-", "Ontology-to-tools compilation for executable semantic constraint enforcement in LLM agents",
     "University of Cambridge, CARES Singapore, MIT, CMCL",
     "论文", "产学合作", ["构造方式"],
     ["ontology", "tool-interface"],
     "https://arxiv.org/abs/2602.03439",
     "academic-2602.03439-ontology-to-tools", "提出将本体描述编译为可执行工具接口的原型方法，使智能体调用工具时可应用语义约束。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-01", "2026-06-04", "Ontology-Constrained Neural Reasoning in Enterprise Agentic Systems: A Neurosymbolic Architecture for Domain-Grounded AI Agents",
     "Golden Gate University, Foundation AgenticOS, Novartis",
     "论文", "产学合作", ["构造方式", "应用内部"],
     ["ontology"],
     "https://arxiv.org/abs/2604.00555",
     "academic-2604.00555-ontology-constrained-reasoning", "介绍将神经网络与符号本体结合的企业智能体架构，用领域知识约束推理过程。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-17", "2026-04-20", "Integrating Graphs, Large Language Models, and Agents: Reasoning and Retrieval",
     "Canadian Institute for Cybersecurity, University of New Brunswick",
     "论文", "学界", ["应用内部"],
     ["ontology", "RAG", "survey"],
     "https://arxiv.org/abs/2604.15951",
     "academic-2604.15951-graphs-llms-agents", "综述图结构、大语言模型与智能体在推理和信息检索中的结合方式，并归纳相关研究方向。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-13", "2026-09-20", "Codex: lightweight coding agent that runs in your terminal",
     "OpenAI",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/openai/codex",
     "vendor-openai-codex", "OpenAI 的本地终端编程智能体，可在代码仓库中协助理解和修改代码并执行开发任务。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-02-22", "2026-09-20", "Claude Code: an agentic coding tool that lives in your terminal",
     "Anthropic",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/anthropics/claude-code",
     "vendor-anthropic-claude-code", "Anthropic 的终端编程智能体，可理解代码库、执行开发任务、解释代码并处理 Git 工作流。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-17", "2026-09-20", "Gemini CLI: an open-source AI agent that brings the power of Gemini directly into your terminal",
     "Google",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/google-gemini/gemini-cli",
     "vendor-google-gemini-cli", "Google 的开源终端 AI 智能体，为命令行提供 Gemini 模型驱动的交互式开发与工具操作能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-06-26", "2026-09-20", "Qwen Code: an open-source AI coding agent that lives in your terminal",
     "Alibaba (QwenLM)",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/QwenLM/qwen-code",
     "vendor-qwen-code", "提供基于 Qwen 的开源终端编程智能体，可在命令行中理解项目并执行软件开发任务。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-04-12", "2026-09-20", "Dify: build agentic workflows and RAG pipelines with rich AI model and tool support",
     "LangGenius",
     "文档", "厂商", ["构造方式", "应用内部"],
     ["orchestration", "RAG", "context-engineering"],
     "https://github.com/langgenius/dify",
     "vendor-langgenius-dify", "提供可视化平台来构建和运行 AI 应用，支持智能体工作流、检索增强生成、模型及工具连接。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-01-19", "2026-01-27", "UI-TARS: pioneering automated GUI interaction with native agents",
     "ByteDance",
     "文档", "厂商", ["界面与接入"],
     ["tool-interface"],
     "https://github.com/bytedance/UI-TARS",
     "vendor-bytedance-ui-tars", "介绍用于图形界面交互的视觉智能体模型与系统，使模型根据屏幕内容生成界面操作。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-13", "2026-09-17", "DeepSeek Harness: everything is a plugin",
     "DeepSeek AI",
     "文档", "厂商", ["构造方式", "界面与接入"],
     ["tool-interface", "orchestration"],
     "https://github.com/deepseek-ai/deepseek-harness",
     "vendor-deepseek-harness", "DeepSeek 开发的开源智能体运行框架，以插件架构组织功能；仓库说明当前处于开发预览阶段。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-17", "2026-08-18", "Security Assessment of DeepSeek Harness with A.I.G: Evaluating Resistance to Indirect Prompt Injection",
     "Tencent Zhuque Lab",
     "论文", "厂商", ["安全与攻防", "构造方式"],
     ["tool-interface", "empirical-study"],
     "https://arxiv.org/abs/2608.16393",
     "academic-2608.16393-deepseek-harness-security", "通过受控间接提示注入测试评估 DeepSeek Harness，分析不同内容通道、攻击方法和运行轨迹下的防护表现。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-03", "2026-06-22", "MCP-SandboxScan: WASM-based Secure Execution and Runtime Analysis for MCP Tools",
     "University of Glasgow, Aarhus University",
     "论文", "学界", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2601.01241",
     "academic-2601.01241-mcp-sandboxscan", "提出基于 WebAssembly 的 MCP 工具安全执行与运行时分析框架，用于隔离工具并检查其行为。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-08", "-", "Internal Representations as Indicators of Hallucinations in Agent Tool Selection",
     "Amazon",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.05214",
     "academic-2601.05214-tool-selection-hallucination", "研究模型内部表示能否用于识别工具选择幻觉，包括错误工具、无效参数和绕过工具调用等情况。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-12", "-", "MCP-ITP: An Automated Framework for Implicit Tool Poisoning in MCP",
     "University of Science and Technology of China",
     "论文", "学界", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2601.07395",
     "academic-2601.07395-mcp-itp-tool-poisoning", "提出自动化的 MCP 隐式工具投毒测试框架，研究注册阶段工具元数据中的恶意指令如何影响智能体。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-12", "-", "Towards Verifiably Safe Tool Use for LLM Agents",
     "Georgia Institute of Technology, Carnegie Mellon University",
     "论文", "学界", ["安全与攻防", "构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.08012",
     "academic-2601.08012-verifiably-safe-tool-use", "研究如何形式化描述并验证 LLM 智能体的工具使用安全，重点讨论工具操作可能造成的数据泄露和记录修改等风险。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-13", "2026-04-19", "ACE-Router: Generalizing History-Aware Routing from MCP Tools to the Agent Web",
     "Zhejiang University, Shanghai Jiao Tong University, Huawei Technologies, Sun Yat-sen University, Nanyang Technological University, Hangzhou Dianzi University",
     "论文", "产学合作", ["协议与生态", "构造方式"],
     ["MCP", "tool-interface"],
     "https://arxiv.org/abs/2601.08276",
     "academic-2601.08276-ace-router", "提出历史感知的智能体路由方法，使系统能够在大量 MCP 工具和服务中选择合适目标。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-14", "-", "Beyond Rule-Based Workflows: An Information-Flow-Orchestrated Multi-Agents Paradigm via Agent-to-Agent Communication from CORAL",
     "Coral Protocol, Brunel University of London, University of Luxembourg, University of Hull, National University of Computer and Emerging Sciences",
     "论文", "产学合作", ["构造方式", "协议与生态"],
     ["orchestration"],
     "https://arxiv.org/abs/2601.09883",
     "academic-2601.09883-information-flow-orchestration", "提出以信息流为核心的多智能体协作范式，讨论如何减少对预先枚举状态和路由规则的依赖。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-15", "-", "Structure and Diversity Aware Context Bubble Construction for Enterprise Retrieval Augmented Systems",
     "Bravada Group, Eye Dream Pty Ltd",
     "论文", "厂商", ["应用内部"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2601.10681",
     "academic-2601.10681-context-bubble-enterprise-rag", "提出面向企业检索增强系统的上下文组装方法，利用结构信息和多样性约束构建连贯的检索内容。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-16", "2026-03-11", "Beyond Max Tokens: Stealthy Resource Amplification via Tool Calling Chains in LLM Agents",
     "Nanyang Technological University, University of Illinois Urbana-Champaign, Hong Kong University of Science and Technology, Shanghai Jiao Tong University",
     "论文", "学界", ["安全与攻防"],
     ["tool-interface"],
     "https://arxiv.org/abs/2601.10955",
     "academic-2601.10955-resource-amplification-tool-chains", "分析智能体多轮工具调用链可能被用于隐蔽放大资源消耗的方式，并研究相关拒绝服务风险。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-16", "2026-01-20", "Institutional AI: Governing LLM Collusion in Multi-Agent Cournot Markets via Public Governance Graphs",
     "DEXAI Icaro Lab, Sapienza University of Rome, Sant'Anna School of Advanced Studies, VU Amsterdam",
     "论文", "产学合作", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.11369",
     "academic-2601.11369-institutional-ai-collusion", "构建多智能体 Cournot 市场实验框架，研究公共治理图如何影响智能体间的协同行为。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-06", "2026-01-22", "Enhancing Model Context Protocol (MCP) with Context-Aware Server Collaboration",
     "University of Chicago",
     "论文", "学界", ["协议与生态"],
     ["MCP", "context-engineering"],
     "https://arxiv.org/abs/2601.11595",
     "academic-2601.11595-context-aware-mcp-collaboration", "提出为 MCP 服务器协作增加共享上下文机制，使智能体可在多服务器任务中传递任务相关状态。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-20", "-", "The Orchestration of Multi-Agent Systems: Architectures, Protocols, and Enterprise Adoption",
     "Skan AI",
     "论文", "厂商", ["协议与生态", "构造方式"],
     ["orchestration", "survey"],
     "https://arxiv.org/abs/2601.13671",
     "academic-2601.13671-orchestration-multi-agent-systems", "整理多智能体编排的架构、协议和企业采用情况，并提出包含规划、策略、状态和质量管理的编排框架。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-21", "-", "Interoperable Architecture for Digital Identity Delegation for AI Agents with Blockchain Integration",
     "Universidad de Los Andes",
     "论文", "学界", ["安全与攻防"],
     ["authorization"],
     "https://arxiv.org/abs/2601.14982",
     "academic-2601.14982-digital-identity-delegation", "提出面向 AI 智能体的跨系统数字身份委托架构，讨论如何实现有边界、可审计的权限转授。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-21", "-", "Securing LLM-as-a-Service for Small Businesses: An Industry Case Study of a Distributed Chatbot Deployment Platform",
     "RMIT University",
     "论文", "学界", ["安全与攻防", "运行与问责"],
     ["empirical-study"],
     "https://arxiv.org/abs/2601.15528",
     "academic-2601.15528-securing-llmaas-small-business", "以面向小企业的多租户聊天机器人平台为案例，讨论 LLM 服务部署中的基础设施、安全和运维设计。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-22", "2026-05-17", "Agentic AI Governance and Lifecycle Management in Healthcare",
     "University of the Cumberlands",
     "论文", "学界", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.15630",
     "academic-2601.15630-agentic-governance-healthcare", "提出面向医疗机构的智能体治理与生命周期管理框架，讨论智能体登记、责任划分和权限控制。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-24", "-", "Towards a Declarative Agentic Layer for Intelligent Agents in MCP-Based Server Ecosystems",
     "Universidad de Granada",
     "论文", "学界", ["构造方式", "协议与生态"],
     ["MCP", "orchestration"],
     "https://arxiv.org/abs/2601.17435",
     "academic-2601.17435-declarative-agentic-layer", "研究在 MCP 服务器生态中加入声明式智能体层，以结构化方式描述任务和协调智能体行动。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-24", "-", "Breaking the Protocol: Security Analysis of the Model Context Protocol Specification and Prompt Injection Vulnerabilities in Tool-Integrated LLM Agents",
     "No affiliation stated (Narek Maloyan, Dmitry Namiot)",
     "论文", "个人", ["安全与攻防", "协议与生态"],
     ["MCP"],
     "https://arxiv.org/abs/2601.17549",
     "academic-2601.17549-breaking-the-protocol-mcp", "分析 MCP 规范与工具集成式 LLM 智能体的安全问题，讨论协议权限声明和提示注入等风险。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-25", "-", "Faramesh: A Protocol-Agnostic Execution Control Plane for Autonomous Agent Systems",
     "The Faramesh Labs",
     "论文", "厂商", ["构造方式", "运行与问责"],
     ["orchestration"],
     "https://arxiv.org/abs/2601.17744",
     "academic-2601.17744-faramesh-control-plane", "提出面向自主智能体系统的协议无关执行控制层，在产生实际副作用前对行动进行授权判断。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-29", "-", "Delegation Without Living Governance",
     "AiSuNe Foundation",
     "论文", "社区与非营利", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2601.21226",
     "academic-2601.21226-delegation-without-living-governance", "讨论智能体系统中的治理、责任和人类参与问题，并论述静态规则对快速自主行动的适用边界。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-30", "2026-05-18", "Whispers of Wealth: Red-Teaming Google's Agent Payments Protocol via Prompt Injection",
     "University of Georgia",
     "论文", "学界", ["安全与攻防", "协议与生态"],
     ["payments"],
     "https://arxiv.org/abs/2601.22569",
     "academic-2601.22569-red-teaming-ap2", "对 Google Agent Payments Protocol 开展提示注入红队测试，检查直接和间接攻击对智能体支付流程的影响。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-30", "-", "TessPay: Verify-then-Pay Infrastructure for Trusted Agentic Commerce",
     "University of Oxford, Indian Institute of Technology Delhi, Tesseris.org",
     "论文", "产学合作", ["协议与生态", "商业与组织"],
     ["payments"],
     "https://arxiv.org/abs/2602.00213",
     "academic-2602.00213-tesspay-verify-then-pay", "提出面向智能体商业交易的验证后支付基础设施，讨论任务委托、服务发现和交易信任等环节。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-01-31", "-", "Engineering AI Agents for Clinical Workflows: A Case Study in Architecture, MLOps, and Governance",
     "A3Data, CEFET-MG",
     "论文", "产学合作", ["构造方式", "运行与问责"],
     ["empirical-study"],
     "https://arxiv.org/abs/2602.00751",
     "academic-2602.00751-clinical-workflow-agents", "以临床工作流中的 AI 智能体为案例，介绍系统架构、机器学习运维和治理方面的工程实践。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-01", "-", "SMCP: Secure Model Context Protocol",
     "Huazhong University of Science and Technology",
     "论文", "学界", ["安全与攻防", "协议与生态"],
     ["MCP"],
     "https://arxiv.org/abs/2602.01129",
     "academic-2602.01129-smcp-secure-mcp", "提出安全版模型上下文协议设计，讨论智能体工具连接中的认证、授权、隐私和安全控制。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-06", "2026-06-17", "Graphs Don't Stay Secret: Practical Subgraph Reconstruction Attacks on Defended Graph RAG",
     "KAIST, National Security Research Institute",
     "论文", "学界", ["应用内部", "安全与攻防"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2602.06495",
     "academic-2602.06495-subgraph-reconstruction-graphrag", "研究攻击者如何通过 Graph RAG 查询重建其底层知识图谱中的子图，并评估相关防护方式。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式、AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-16", "2026-08-26", "Corpus2Skill: Distilling Enterprise Knowledge into Navigable Agent Skills for QA and RAG",
     "Magellan Technology Research Institute",
     "论文", "厂商", ["应用内部", "构造方式"],
     ["RAG", "context-engineering"],
     "https://arxiv.org/abs/2604.14572",
     "academic-2604.14572-corpus2skill", "提出将企业知识语料离线整理为层级技能目录、再由智能体逐层检索的问答与检索架构。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-05-28", "2026-08-10", "On Effectiveness and Efficiency of Agentic Tool-calling and RL Training",
     "LMU Munich, Munich Center for Machine Learning, University of Illinois Urbana-Champaign, Amazon, University of Sheffield",
     "论文", "产学合作", ["构造方式"],
     ["tool-interface", "benchmark"],
     "https://arxiv.org/abs/2606.00135",
     "academic-2606.00135-agentic-tool-calling-rl", "从评测有效性和训练效率两个角度研究智能体工具调用，分析评测流程及强化学习训练方法。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-16", "-", "Characterizing Network Centralization and Observability in the Remote MCP Ecosystem",
     "University of Calgary",
     "论文", "学界", ["协议与生态", "运行与问责"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.19100",
     "academic-2609.19100-remote-mcp-centralization", "通过目录元数据、被动合规信号和实时漏洞分析研究远程 MCP 生态的网络结构与可观测性。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-11-30", "2026-09-15", "awesome-mcp-servers: a collection of MCP servers",
     "Frank Fiegel (punkpeye)",
     "清单", "个人", ["协议与生态"],
     ["MCP", "curated-list"],
     "https://github.com/punkpeye/awesome-mcp-servers",
     "community-punkpeye-mcp-servers", "按类别收集 MCP 服务器项目，为不同客户端和用途提供可浏览的服务器目录。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-15", "-", "Introducing System One Models & Jev",
     "TypeSafe AI",
     "文章", "厂商", ["构造方式", "应用内部"],
     ["decision-model", "tool-interface"],
     "https://typesafe.ai/blog/introducing-system-one-models-and-jev",
     "vendor-typesafe-jev-announcement", "TypeSafe AI 介绍 System One 模型系列和 Jev，说明其面向软件自动化提供结构化决策输出。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-15", "-", "Introduction — TypeSafe AI (Jev developer documentation)",
     "TypeSafe AI",
     "文档", "厂商", ["构造方式"],
     ["decision-model", "tool-interface"],
     "https://docs.typesafe.ai/introduction",
     "vendor-typesafe-jev-docs", "介绍 Jev API 的状态输入和类型化问题接口，以及供程序和编程智能体使用结构化回答的方式。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-14", "-", "Salesforce Koa: An Enterprise Language Model for Agentic Tool Use",
     "Salesforce",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2609.15066",
     "academic-2609.15066-salesforce-koa", "介绍 Salesforce Koa 的模型构建方法，描述其以 Nemotron 基础模型为起点并通过强化学习适配企业工具使用。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-15", "-", "Announcing Koa: Salesforce’s First CRM Reasoning Model, Built on NVIDIA Nemotron",
     "Salesforce",
     "文章", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://www.salesforce.com/news/press-releases/2026/09/15/koa-reasoning-model/",
     "vendor-salesforce-koa-announcement", "Salesforce 与 NVIDIA 发布 Koa CRM 推理模型，说明其面向企业多步骤任务并基于 Salesforce 业务数据训练。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-16", "-", "Why We Post-Trained Our Own Reasoning Model (Koa)",
     "Salesforce",
     "文章", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://www.salesforce.com/news/stories/why-we-post-trained-our-own-reasoning-model/",
     "vendor-salesforce-koa-post-training", "Salesforce 介绍为企业工作训练 Koa 推理模型的原因、后训练流程及其与通用模型的区别。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-14", "-", "Authorization Architectures for Tool-Using AI Agents",
     "Westcliff University, University of the Cumberlands, Delta Air Lines, Georgia Institute of Technology",
     "论文", "产学合作", ["安全与攻防"],
     ["authorization", "survey"],
     "https://arxiv.org/abs/2609.15906",
     "academic-2609.15906-authorization-architectures", "提出面向工具型 AI 智能体的授权架构，讨论如何将行动绑定到用户主体、权限范围和审计记录。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-14", "-", "When Tool Calls Succeed but Workflows Fail: Anomalies at the Agent-Tool Boundary",
     "AVIV Group, independent researcher",
     "论文", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://arxiv.org/abs/2609.15397",
     "academic-2609.15397-tool-calls-succeed-workflows-fail", "研究重试、并发和部分失败时智能体工作流与外部工具状态不一致的情况，包括操作遗漏、重复及已取消操作残留。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-13", "-", "A Two-Dimensional Study of the Model Context Protocol: Publication and Adoption",
     "Luxembourg Institute of Science and Technology, University of Luxembourg",
     "论文", "学界", ["协议与生态"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.14721",
     "academic-2609.14721-mcp-publication-adoption", "对 MCP 相关论文和 GitHub 仓库进行纵向统计，分析研究发表、开源采用及两者之间的关系。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-13", "-", "The Stochastic Deputy: Structural Tenant Isolation for Tool-Using LLM Agents",
     "Fandaqah, Heidelberg University",
     "论文", "产学合作", ["安全与攻防"],
     ["MCP", "authorization"],
     "https://arxiv.org/abs/2609.14780",
     "academic-2609.14780-stochastic-deputy-tenant-isolation", "提出结构化多租户隔离方法，将租户范围绑定到已验证凭据并在服务器侧强制执行，而不让模型自行选择租户标识。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-12", "-", "Same Name, Different Server: A Security Census of Silent Drift in MCP",
     "Texas Tech University",
     "论文", "学界", ["协议与生态", "安全与攻防"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2609.14119",
     "academic-2609.14119-same-name-different-server", "对公开 MCP 注册表中的服务器及版本进行安全普查，研究同名服务器在版本间静默变化的情况。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-10", "-", "Is Bash All You Need? An Empirical Study of Tool Interfaces for Enterprise Digital Worker Agents",
     "Microsoft, Carnegie Mellon University",
     "论文", "产学合作", ["构造方式", "界面与接入"],
     ["tool-interface", "benchmark"],
     "https://arxiv.org/abs/2609.11999",
     "academic-2609.11999-is-bash-all-you-need", "比较企业数字工作任务中的多种智能体工具接口，包括专用类型化工具与通用 shell。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-05", "-", "Intent Drift at SME Scale: Deployment Practice, Not Model Capability, Determines Agentic Compliance",
     "Hong Kong University of Science and Technology",
     "论文", "学界", ["运行与问责", "应用内部"],
     ["regulation", "empirical-study"],
     "https://arxiv.org/abs/2609.05975",
     "academic-2609.05975-intent-drift-sme", "提出适用于受监管小型企业的 Chain of Intent 治理框架，并通过模拟资产管理场景检验部署约束的执行情况。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排、AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-31", "-", "Delegation Without Trust: An Empirical Gap Analysis of Identity, Authorization, and Runtime",
     "VotalAI",
     "论文", "厂商", ["安全与攻防"],
     ["authorization"],
     "https://arxiv.org/abs/2609.00267",
     "academic-2609.00267-delegation-without-trust", "分析多智能体系统在身份、授权和运行时治理上的委托机制，并通过案例评估现有设计缺口。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-25", "-", "Hybrid Semantic Tool Discovery for Enterprise MCP Gateway: Architecture and Implementation",
     "PayPal",
     "论文", "厂商", ["协议与生态", "构造方式"],
     ["MCP", "context-engineering", "tool-interface"],
     "https://arxiv.org/abs/2608.23992",
     "academic-2608.23992-semantic-tool-discovery", "提出企业 MCP 网关的混合语义工具发现架构，讨论如何在大量工具场景下兼顾上下文、认证、策略和可观测性。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-08-22", "2025-10-11", "MCPVerse: An Expansive, Real-World Benchmark for Agentic Tool Use",
     "SenseTime Research",
     "论文", "厂商", ["构造方式"],
     ["MCP", "benchmark"],
     "https://arxiv.org/abs/2508.16260",
     "academic-2508.16260-mcpverse", "构建包含 550 多个真实可执行工具的 MCPVerse 基准，用于评测智能体在现实工具环境中的使用能力。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-22", "-", "From SQL Generation to Tool Selection: A Domain-Oriented Pattern for MCP Servers",
     "No affiliation stated (Bartolomeo Bogliolo)",
     "论文", "个人", ["界面与接入", "构造方式"],
     ["MCP", "tool-interface"],
     "https://arxiv.org/abs/2608.22063",
     "academic-2608.22063-domain-oriented-tooling", "提出面向 MCP 服务器的领域工具模式：以封装业务规则的专用参数化工具替代模型运行时生成通用 SQL。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-19", "-", "Expanding Headless 360: Turning Enterprise Applications into Enterprise Capabilities",
     "Salesforce",
     "文章", "厂商", ["界面与接入"],
     ["headless"],
     "https://www.salesforce.com/news/stories/expanding-headless-360-enterprise-capabilities/",
     "vendor-salesforce-headless-360", "介绍 Salesforce Headless 360 将企业应用能力封装为可供获授权智能体发现和调用的接口。", '原文内容呈现AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-07-28", "-", "Model Context Protocol Specification (version 2026-07-28)",
     "Model Context Protocol",
     "规范", "标准组织", ["协议与生态"],
     ["MCP"],
     "https://modelcontextprotocol.io/specification/latest",
     "standard-mcp-spec-index", "定义 Model Context Protocol 的客户端与服务器通信、消息模式、传输、授权及工具等协议机制。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-06-30", "-", "Benchmarking the Benchmarks: A Validity Audit of Tool-Calling Evaluation",
     "CoreThink AI, Stanford University",
     "论文", "产学合作", ["构造方式"],
     ["benchmark"],
     "https://arxiv.org/abs/2607.02577",
     "academic-2607.02577-benchmark-validity-audit", "对四类工具调用基准开展效度与复现性审计，并以专家复核任务比较评测器结果和人工判断。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-06-08", "-", "Understanding How Enterprises Adopt the Model Context Protocol for LLM-Driven Software Engineering",
     "City University of Hong Kong, Hong Kong Metropolitan University",
     "论文", "学界", ["协议与生态", "构造方式"],
     ["MCP", "empirical-study"],
     "https://arxiv.org/abs/2606.09182",
     "academic-2606.09182-enterprise-mcp-adoption", "通过实证研究分析企业在软件工程场景采用 MCP 的方式、部署挑战、运营风险和从业者经验。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-05-28", "2026-05-28", "Awesome Context Engineering (companion repo)",
     "Institute of Computing Technology CAS, et al.",
     "清单", "学界", ["应用内部", "构造方式"],
     ["context-engineering", "curated-list"],
     "https://github.com/Meirtz/Awesome-Context-Engineering",
     "community-context-engineering-readme", "整理上下文工程相关方法、框架、工具、示例和研究资料，供构建 LLM 应用时查阅。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式、AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-05-13", "-", "ServiceNow opens its full system of action to every AI Agent in the enterprise (Action Fabric)",
     "ServiceNow",
     "文章", "厂商", ["界面与接入", "运行与问责"],
     ["headless"],
     "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-opens-its-full-system-of-action-to-every-AI-Agent-in-the-enterprise/default.aspx",
     "vendor-servicenow-action-fabric", "ServiceNow 发布 Action Fabric，介绍让企业 AI 智能体连接并调用跨系统工作流与操作能力的方案。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-29", "2026-05-02", "The Buy-or-Build Decision, Revisited: How Agentic AI Changes the Economics of Enterprise Software",
     "Stuttgart Media University",
     "论文", "学界", ["商业与组织"],
     ["buy-vs-build"],
     "https://arxiv.org/abs/2604.26482",
     "academic-2604.26482-buy-or-build", "从交易成本和资源基础等理论讨论智能体式 AI 如何改变企业软件的自建或采购决策。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04-26", "-", "Infrastructure for the Agentic Web: Gap Analysis and Architecture from the Agentverse Platform",
     "OpenHub Research",
     "论文", "社区与非营利", ["协议与生态"],
     ["empirical-study", "registry"],
     "https://arxiv.org/abs/2606.20570",
     "academic-2606.20570-agentic-web-infra", "分析 Agentverse 智能体云平台所需的基础设施，并提出面向智能体网络的架构组成。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-04", "-", "SAP API Policy v.4.2026a",
     "SAP",
     "规范", "厂商", ["界面与接入", "协议与生态"],
     ["tool-interface"],
     "https://help.sap.com/doc/sap-api-policy/latest/en-US/API_Policy_latest.pdf",
     "vendor-sap-api-policy", "规定 SAP API 的发布范围、调用限制和安全控制，并说明对自动化及生成式 AI 调用的适用边界。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-03-26", "-", "From Logic Monopoly to Social Contract (working paper, not peer reviewed)",
     "NetX Foundation",
     "论文", "社区与非营利", ["运行与问责"],
     ["risk-framework"],
     "https://arxiv.org/abs/2603.25100",
     "academic-2603.25100-logic-monopoly", "工作论文讨论自主智能体经济中的权力分离和治理结构，并提出以制度安排应对多智能体系统风险。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-03-02", "-", "Good news: AI Will Eat Application Software",
     "a16z",
     "文章", "投资机构", ["商业与组织"],
     ["headless"],
     "https://a16z.com/good-news-ai-will-eat-application-software/",
     "investor-a16z-eat-application-software", "文章讨论生成式 AI 对企业应用软件市场的影响，提出网络效应、品牌和专有数据等因素仍会参与竞争。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-03", "-", "AI Isn't Going to \"Eat\" Software: Agentic AI Needs the Authoritative Data and Rules Inside Enterprise Apps",
     "IDC",
     "报告", "分析机构", ["商业与组织"],
     ["headless"],
     "https://my.idc.com/getdoc.jsp?containerId=US54377825",
     "analyst-idc-landing", "", '原文内容呈现题名涉及智能体式 AI 与企业应用数据规则的关系；正文需登录，纳入依据限于可见落地页信息。，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-24", "-", "The Headless Firm: How AI Reshapes Enterprise Boundaries",
     "Mantix (authors declare a conflict of interest)",
     "论文", "厂商", ["界面与接入", "商业与组织"],
     ["headless"],
     "https://arxiv.org/abs/2602.21401",
     "academic-2602.21401-headless-firm", "提出 Headless Firm 组织模型，讨论协议化智能体如何改变企业组件之间的协调成本和组织边界。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-05-18", "-", "Going Headless? On the Boundaries of Vertical AI Firms",
     "University of Pittsburgh, Ensi.ai",
     "论文", "产学合作", ["界面与接入", "商业与组织", "运行与问责"],
     ["headless"],
     "https://arxiv.org/abs/2605.17812",
     "academic-2605.17812-going-headless", "分析通用智能体将垂直软件中的工作流、领域逻辑和责任机制拆分后，对不同垂直 AI 企业边界的影响。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 对软件产品边界、商业模式或组织分工的影响、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-12-09", "-", "2025: The State of Generative AI in the Enterprise (survey of 495 respondents)",
     "Menlo Ventures",
     "报告", "投资机构", ["商业与组织"],
     ["market-data"],
     "https://menlovc.com/perspective/2025-the-state-of-generative-ai-in-the-enterprise/",
     "investor-menlo-state-of-genai", "Menlo Ventures 基于 495 名受访者的调查报告，汇总企业生成式 AI 的采用、应用场景和支出情况。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-12-09", "-", "OWASP Top 10 for Agentic Applications for 2026",
     "OWASP GenAI Security Project",
     "规范", "社区与非营利", ["安全与攻防"],
     ["risk-framework"],
     "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
     "standard-owasp-top10-agentic", "列出智能体应用的主要安全风险类别，并提供供开发团队和组织使用的风险说明与防护建议。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-11-25", "-", "Securing the Model Context Protocol (MCP): Risks, Controls, and Governance",
     "Vanta, MintMCP, Darktrace",
     "论文", "厂商", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2511.20920",
     "academic-2511.20920-securing-mcp", "梳理 MCP 工具连接引入的安全威胁、相关控制措施和组织治理议题。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-11-05", "-", "Technology Radar: Model Context Protocol (MCP) assessed as Trial",
     "ThoughtWorks",
     "报告", "分析机构", ["协议与生态"],
     ["MCP"],
     "https://www.thoughtworks.com/radar/platforms/model-context-protocol-mcp",
     "analyst-thoughtworks-radar-mcp", "Thoughtworks 技术雷达评估 MCP 的定位和适用场景，并将其列为 Trial 阶段技术。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-08-05", "2025-10-20", "Evolution of AI Agent Registry Solutions: Centralized, Enterprise, and Distributed Approaches",
     "MIT, Cisco, Cleveland State University, et al.",
     "论文", "产学合作", ["协议与生态"],
     ["registry", "survey"],
     "https://arxiv.org/abs/2508.03095",
     "academic-2508.03095-agent-registries", "比较集中式、企业内和分布式 AI 智能体注册表方案，讨论发现、能力协商与身份保障。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-09-11", "-", "Writing effective tools for agents — with agents",
     "Anthropic",
     "文章", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://www.anthropic.com/engineering/writing-tools-for-agents",
     "toolcraft-anthropic-writing-tools", "Anthropic 介绍借助智能体设计和优化智能体工具的实践，并讨论工具质量与评估方法。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-09-01", "-", "An Economy of AI Agents (NBER handbook chapter)",
     "Johns Hopkins University, MIT",
     "论文", "学界", ["商业与组织"],
     ["survey"],
     "https://arxiv.org/abs/2509.01063",
     "academic-2509.01063-economy-of-ai-agents", "经济学手册章节综述 AI 智能体与个人、市场及组织互动的研究进展和待研究问题。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-07-17", "2025-07-21", "A Survey of Context Engineering for Large Language Models",
     "Institute of Computing Technology CAS, Peking University, Tsinghua University, et al.",
     "论文", "学界", ["应用内部"],
     ["context-engineering", "survey"],
     "https://arxiv.org/abs/2507.13334",
     "academic-2507.13334-context-engineering-survey", "对上下文工程进行综述和分类，讨论推理阶段如何选择、组织和优化提供给大语言模型的信息。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-11", "2025-05-02", "Enterprise-Grade Security for the Model Context Protocol (MCP)",
     "Amazon Web Services, Intuit",
     "论文", "厂商", ["安全与攻防"],
     ["MCP"],
     "https://arxiv.org/abs/2504.08623",
     "academic-2504.08623-enterprise-mcp-security", "提出 MCP 企业安全框架，梳理协议集成中的风险并汇总相应的控制和缓解策略。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-05-06", "-", "From Glue-Code to Protocols: A Critical Analysis of A2A and MCP Integration",
     "Kennesaw State University",
     "论文", "学界", ["协议与生态"],
     ["MCP", "A2A"],
     "https://arxiv.org/abs/2505.03864",
     "academic-2505.03864-a2a-mcp-integration", "分析 A2A 与 MCP 在多智能体系统中的分工、互补关系及组合时的集成问题。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-02-05", "2026-09-16", "MCP Registry: a community driven registry service for Model Context Protocol servers",
     "Model Context Protocol",
     "文档", "标准组织", ["协议与生态"],
     ["MCP", "registry"],
     "https://github.com/modelcontextprotocol/registry",
     "standard-mcp-registry-design-principles", "提供 MCP 服务器注册服务，使 MCP 客户端能够发现和获取已发布服务器条目。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-03-25", "2026-09-16", "A2A Protocol",
     "Linux Foundation",
     "文档", "标准组织", ["协议与生态"],
     ["A2A"],
     "https://a2a-protocol.org/latest/",
     "standard-a2a-protocol-home", "定义 Agent2Agent 开放协议，使不同厂商的智能体能够发现彼此、交换任务并协作。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-08-25", "-", "ACP Joins Forces with A2A Under the Linux Foundation",
     "BeeAI project (led by IBM Research)",
     "文章", "标准组织", ["协议与生态"],
     ["ACP", "A2A"],
     "https://github.com/orgs/i-am-bee/discussions/5",
     "announce-acp-joins-a2a", "公告说明 ACP 项目将与 A2A 在 Linux Foundation 旗下协同，讨论协议项目整合安排。", '原文内容呈现AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-05-01", "-", "Extend Atlassian into any AI assistant using MCP",
     "Atlassian",
     "文档", "厂商", ["界面与接入", "运行与问责"],
     ["MCP"],
     "https://www.atlassian.com/platform/remote-mcp-server",
     "vendor-atlassian-remote-mcp", "介绍 Atlassian Remote MCP Server 如何将获授权的 Jira、Confluence 等数据和操作接入外部 AI 助手。", '原文内容呈现AI 接入软件能力或用户界面的具体方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-02-12", "-", "Salesforce Agentforce Pricing (per-conversation)",
     "Salesforce",
     "文档", "厂商", ["商业与组织"],
     ["pricing"],
     "https://www.salesforce.com/agentforce/pricing/",
     "vendor-salesforce-agentforce-pricing", "列出 Salesforce Agentforce 的产品套餐和按对话计费选项，供客户了解智能体产品定价方式。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-05-22", "-", "Fin AI Agent Pricing (per-outcome)",
     "Intercom",
     "文档", "厂商", ["商业与组织"],
     ["pricing"],
     "https://fin.ai/pricing",
     "vendor-intercom-fin-pricing", "列出 Intercom Fin 客服智能体按解决结果计费的价格和服务方案。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2023-11-06", "-", "Function calling",
     "OpenAI",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://platform.openai.com/docs/guides/function-calling",
     "toolcraft-openai-function-calling", "介绍 API 函数调用机制，使模型可选择应用预先定义的函数并以结构化参数请求外部系统执行。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2021-08-12", "-", "AI Risk Management Framework",
     "NIST",
     "规范", "标准组织", ["运行与问责"],
     ["risk-framework"],
     "https://www.nist.gov/itl/ai-risk-management-framework",
     "standard-nist-ai-rmf", "提供组织级 AI 风险管理框架，按治理、识别、测量和管理等功能组织 AI 生命周期风险工作。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-08-10", "-", "Implementation Timeline — EU Artificial Intelligence Act",
     "Future of Life Institute (tracker)",
     "清单", "社区与非营利", ["运行与问责"],
     ["regulation"],
     "https://artificialintelligenceact.eu/implementation-timeline/",
     "community-eu-ai-act-timeline", "整理欧盟 AI Act 的适用义务和实施时间节点，按法规要求列出不同阶段的日期安排。", '原文内容呈现AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-06-03", "-", "The State Of Agentic AI In 2026 (public blog post)",
     "Forrester",
     "文章", "分析机构", ["商业与组织"],
     ["market-data"],
     "https://www.forrester.com/blogs/the-state-of-agentic-ai-in-2026-companies-are-chasing-few-are-catching/",
     "analyst-forrester-state-of-agentic-ai", "Forrester 文章讨论企业智能体 AI 的采用和规模化之间的差距，并介绍报告对推广障碍的分析。", '原文内容呈现AI 对软件产品边界、商业模式或组织分工的影响，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-02-10", "2026-09-12", "awesome-ai-agent-papers: a curated collection of AI agent research papers released in 2026",
     "VoltAgent",
     "清单", "厂商", ["应用内部", "构造方式", "运行与问责"],
     ["curated-list"],
     "https://github.com/VoltAgent/awesome-ai-agent-papers",
     "community-voltagent-agent-papers", "按主题整理 2026 年发布的 AI 智能体研究论文，并提供可浏览的论文清单。", '原文内容呈现AI 改变软件内部功能、流程或数据处理的方式、AI 参与软件设计、实现、测试或工程流程的方式、AI 软件的运行治理、授权、监测或责任安排，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2025-04-08", "2026-03-03", "awesome-mcp-security",
     "Maciej Pulikowski (Puliczek)",
     "清单", "个人", ["安全与攻防"],
     ["MCP", "curated-list"],
     "https://github.com/Puliczek/awesome-mcp-security",
     "community-puliczek-mcp-security", "整理 MCP 安全相关的规范说明、论文、工具、视频和文章链接。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-03-14", "2026-03-14", "Awesome MCP Security: security scores for 800+ MCP servers",
     "Agentseal",
     "清单", "厂商", ["安全与攻防", "协议与生态"],
     ["MCP", "curated-list"],
     "https://github.com/getagentseal/awesome-mcp-security",
     "community-agentseal-mcp-server-scores", "整理 MCP 服务器的安全评分和相关资源，覆盖项目 README 所列的 800 多个服务器。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 系统与软件接口、协议或工具生态的演进，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2024-07-16", "-", "百炼文档（兼容 OpenAI 接口规范）",
     "阿里云",
     "文档", "厂商", ["构造方式"],
     ["tool-interface"],
     "https://help.aliyun.com/zh/model-studio/",
     "platform-aliyun-bailian", "阿里云百炼文档介绍模型服务平台、兼容 OpenAI 的 API，以及创建智能体和知识库问答应用的方法。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-09-18", "-", "网络安全标准实践指南——智能体系统开发安全指南（征求意见稿 v1.0-202609）",
     "全国网络安全标准化技术委员会",
     "规范", "标准组织", ["安全与攻防", "界面与接入"],
     ["regulation"],
     "https://www.tc260.org.cn/tc260/tzgg/202609/e5b82ae7aca244d19d36b39575cbb458.shtml",
     "standard-tc260-agent-dev-security-guide", "该征求意见稿旨在为智能体系统的安全开发提供实践指引，通知说明其面向社会公开征求意见。", '原文内容呈现AI 软件或智能体的威胁、安全控制与防护机制、AI 接入软件能力或用户界面的具体方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-07", "-", "Apeiron: A Scalable LLM-agentic Framework for Autonomous Full-lifecycle Demand-optimized Application Synthesis",
     "Dartmouth College; Microsoft",
     "论文", "产学合作", ["构造方式"],
     ["benchmark", "empirical-study"],
     "https://aclanthology.org/2026.findings-acl.188/",
     "paper-apeiron",
     "提出用计算机操作智能体模拟用户需求、结合代码交互轨迹评估，并在持续交付中约束变更的应用合成框架；论文报告了多场景基准与用户研究结果。", '原文内容呈现AI 参与软件设计、实现、测试或工程流程的方式，与本仓记录 AI 如何改变软件开发的范围直接相关。'),
    ("2026-08-25", "-", "Model-Based Agentic Software Engineering",
     "Purdue University; Amazon Robotics",
     "论文", "产学合作", ["构造方式", "运行与问责"],
     ["orchestration", "risk-framework"],
     "https://arxiv.org/abs/2608.25174",
     None, "提出 MAGE 理论框架，通过显式表示工程知识，并以约束、传感器、验证器和准入门控制智能体工作；研究基于一个纵向案例及六个工业案例的比较分析。", "研究直接讨论如何把工程知识、验证证据和权限约束纳入编码 Agent 的工作环境，属于 AI 改变软件工程流程与治理方式的一手研究。"),
    ("2026-09-02", "-", "How we make AI coding more cost efficient without sacrificing task quality",
     "GitHub",
     "文章", "厂商", ["构造方式"],
     ["orchestration", "empirical-study"],
     "https://github.blog/ai-and-ml/github-copilot/how-we-make-ai-coding-more-cost-efficient-without-sacrificing-task-quality/",
     None, "GitHub 介绍 Copilot 编码 Agent 在工具输出压缩、提示词缩短和后台任务通知等方面的改动，并报告离线基准与线上实验的评估方法和结果。", "文章给出编码 Agent 的上下文管理、任务编排和评估实践，直接记录 AI 编程工具的工程实现如何变化。"),
    ("2026-09-22", "2026-09-22", "MCP Bastion",
     "Matthew0822",
     "文档", "个人", ["安全与攻防", "协议与生态"],
     ["MCP", "authorization", "observability"],
     "https://github.com/Matthew0822/MCPBastion",
     None, "提供本地 MCP 消息网关，按策略允许、拒绝或脱敏工具调用，并记录审计事件；仓库说明其只处理 stdio JSON-RPC 消息，不负责传输桥接或服务器启动。", "它把策略控制和审计放到 MCP 工具调用路径中，具体呈现了智能体接入软件工具时的运行安全设计。"),
    ("2026-09-20", "2026-09-21", "ZCode",
     "Z.ai",
     "文档", "厂商", ["构造方式"],
     ["orchestration"],
     "https://github.com/zai-org/ZCode",
     None, "提供 AI 编程工作台，包含桌面应用、浏览器界面和终端 Agent；仓库包含客户端、后端、共享 UI 以及 Agent CLI 与运行时源码。", "项目将编程 Agent 作为桌面、浏览器和终端工作台的核心能力，具体体现 AI 对软件开发工具形态与交互入口的改变。"),
    ("2026-09-18", "2026-09-23", "agent-chaperone",
     "agent-chaperone",
     "文档", "个人", ["安全与攻防", "运行与问责"],
     ["MCP", "observability"],
     "https://github.com/agent-chaperone/agent-chaperone",
     None, "提供 MCP 代理和客户端 Hook，在工具调用执行前及结果交给智能体前进行筛查，并将概率判断、策略阈值和审计记录写入本地日志；仓库附有公开基准和人工标注集的评测结果。", "项目在 Agent 与工具之间加入可配置筛查、运行日志和评测机制，呈现智能体软件的安全控制如何进入实际开发与运行流程。"),
    ("2026-09-19", "2026-09-19", "Jev Security Scan",
     "win4r",
     "文档", "个人", ["安全与攻防"],
     ["MCP", "risk-framework"],
     "https://github.com/win4r/jev-security-scan",
     None, "扫描 Agent Skill、MCP 配置与源码中的提示注入、凭据读取、非预期外传和动态执行等行为，输出文件位置、脱敏证据、风险类别及未扫描范围；本地模式不联网，且不执行目标代码。", "该工具把 Agent Skill 和 MCP 代码的安全检查纳入安装或运行前流程，直接对应 AI 开发工具链的安全保障变化。"),
    ("2026-09-16", "2026-09-23", "Migrating the GitHub Copilot runtime to Rust, using Copilot",
     "GitHub",
     "文章", "厂商", ["构造方式"],
     ["orchestration", "empirical-study"],
     "https://github.blog/ai-and-ml/generative-ai/migrating-the-github-copilot-runtime-to-rust-using-copilot/",
     None, "记录使用 Copilot 将共享智能体运行时从 TypeScript 分批迁移至 Rust 的过程，说明临时互操作层、SDK 接口、渐进发布与测试安排，并给出拉取请求和会话日志数据。",
     "文章以已落地的运行时迁移为对象，展示编码 Agent 如何参与跨组件改写、并行协作和验证，以及共享 Agent 运行时的构造方式；其迁移步骤和日志数据提供了具体工程证据。"),
    ("2026-07-04", "2026-09-15", "Security Principal and Verifier Binding for Agent Communication Protocols (Internet-Draft)",
     "Songbo Bu",
     "规范", "个人", ["安全与攻防", "协议与生态"],
     ["authorization"],
     "https://datatracker.ietf.org/doc/draft-bu-agentproto-security-principal-binding/07/",
     None, "这份个人 Internet-Draft 为智能体通信协议中的身份、授权、委托和行动证据定义验证者矩阵，逐项标明声明载体、验证者、绑定、新鲜度和失败行为，并给出组合规则与测试向量。",
     "草案将智能体协议中的授权与身份主张拆成可逐项验证的安全声明，规定跨协议组合时的结果和失效边界，直接对应协议生态的安全设计；原文还列出版本固定的测试向量供核查。"),
    ("2026-09-25", "-", "A new, no-compromises database architecture for the agentic era",
     "Google Cloud",
     "文章", "厂商", ["应用内部", "安全与攻防"],
     ["MCP", "sandbox"],
     "https://cloud.google.com/blog/products/databases/alloydbs-agentic-database-architecture",
     None, "介绍 AlloyDB 面向智能体查询的架构：以只读微虚拟机节点访问实时生产数据，并在计算和存储路径上与主集群隔离；文章给出并发索引查询与扩容测试的设置和结果。",
     "原文具体说明 Agent 突发查询如何改变数据库计算、存储与生产负载的隔离方式，并提供节点扩容测试；它对应应用内部数据架构及智能体访问生产数据的隔离控制。"),
    ("2026-09-24", "-", "Control the Harness, Control the Cost: Routing and Governing AI Coding Agents in the Enterprise",
     "Accenture Responsible AI; Accenture Americas Advanced AI Practice; Harvard Extension School, Harvard University",
     "论文", "产学合作", ["构造方式", "商业与组织"],
     ["orchestration", "pricing", "buy-vs-build"],
     "https://arxiv.org/abs/2609.28919",
     None, "提出面向编码 Agent 的缓存感知模型路由方法，在会话开始、旁路任务和子智能体启动时选择模型；用公开会话数据和合成任务模拟企业席位成本，并列出方法与适用限制。",
     "论文把提示缓存、子智能体和模型选择纳入编码 Agent 的运行架构及企业成本决策，并公开路由规则、成本模型和模拟设定；这些具体机制对应开发工具构造与软件采购治理。"),
    ("2026-09-23", "2026-09-24", "Engineering a security harness for AI coding agents",
     "Endor Labs",
     "文章", "厂商", ["安全与攻防", "运行与问责"],
     ["authorization", "risk-framework"],
     "https://www.endorlabs.com/learn/engineering-a-security-harness-for-ai-coding-agents",
     None, "提出安全编码 Agent 的七项设计问题，按读取、建议、准备、发布、执行划分权限，并说明证据获取、验证门、审批、故障恢复和版本管理的工作流。",
     "文章以依赖修复为例，具体规定 Agent 从分析到改动、发布时所需的证据与授权边界，以及运行后的评估和中断处理，对应开发智能体的安全控制与问责流程。"),
    ("2026-09-18", "-", "Changing the game: Using agentic AI to secure infrastructure code",
     "Google Cloud",
     "文章", "厂商", ["构造方式", "安全与攻防"],
     ["orchestration", "context-engineering"],
     "https://cloud.google.com/blog/topics/systems/using-ai-agents-to-secure-google-infrastructure/",
     None, "介绍在代码提交前使用智能体扫描安全问题，结合局部威胁模型、调用图和结构化规则做分层验证；夜间再扫描跨变更问题，并由修复 Agent 提交补丁供人工审查。",
     "原文给出 Google 将扫描、结构化验证、修复建议和人工审查接入代码变更流程的具体步骤，呈现 AI 如何改变基础设施代码的开发与安全检查。"),
    ("2026-09-24", "-", "AI-powered fuzzing with the GitHub Security Lab Taskflow Agent",
     "GitHub Security Lab",
     "文章", "厂商", ["构造方式", "安全与攻防"],
     ["orchestration", "MCP"],
     "https://github.blog/security/application-security/ai-powered-fuzzing-with-the-github-security-lab-taskflow-agent/",
     None, "介绍面向 C/C++ 项目的智能体模糊测试流程：自动生成测试入口与 harness，运行 AFL++，按覆盖率反馈调整输入和 harness，并对崩溃去重、复现及生成待人工审查的报告；配套实现已公开。",
     "原文给出驱动脚本、分阶段任务流、MCP 执行工具和 SQLite 状态库的分工，并说明覆盖率循环与崩溃分诊规则；这些具体实现呈现 AI 如何进入软件安全测试流程。"),
    ("2026-09-24", "-", "When chat is the wrong UI",
     "GitHub",
     "文章", "厂商", ["界面与接入", "构造方式"],
     ["tool-interface", "orchestration"],
     "https://github.blog/ai-and-ml/github-copilot/when-chat-is-the-wrong-ui/",
     None, "以 GitHub Copilot app 的 Canvas 为例，说明可由智能体生成并在应用内运行交互界面；人和智能体可通过共享状态双向操作，文中展示游戏、本地包管理及开发工作流界面的实例。",
     "文章具体描述 Canvas 作为带服务端能力的共享界面，允许用户操作控件、智能体调用界面能力并持续修改工作流；它呈现了 AI 开发工具从聊天窗口扩展到可交互软件界面的机制。"),
    ("2026-09-15", "-", "Introducing Filestore agent volumes: fully managed storage for agent workspaces",
     "Google Cloud",
     "文章", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox", "orchestration"],
     "https://cloud.google.com/blog/products/storage-data-transfer/filestore-agent-volumes",
     None, "介绍面向 Agent 工作区的 Filestore 卷：GKE 沙箱启动时分配并挂载独立的持久文件空间，支持会话恢复及以 POSIX 锁和共享读写方式协作；官方文档说明卷池、卷与私有连接的架构。",
     "原文说明编码 Agent 安装依赖、修改文件和运行测试所需的持久工作区如何随沙箱按需分配、隔离与共享；这为开发智能体的运行存储和多租户安全提供了具体架构。"),
    ("2026-09-24", "-", "Evaluating Agent Skills for Version-Specific Plugin Migration: A Retrospective Study",
     "Tsinghua University; Fudan University; PetroChina Southwest Oil & Gasfield Company, et al.",
     "论文", "产学合作", ["构造方式"],
     ["skills", "benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.30120",
     None, "回顾一个插件升级技能在 16 项版本迁移任务上的 64 份诊断报告，逐项审查 328 个评分判断，并以可执行探针和跨模型盲评检查契约错误及评分敏感性；原始报告和分析脚本在项目仓库公开。",
     "论文把编码 Agent 技能的迁移建议与目标版本契约逐项对应，并检查自动评分能否发现路径边界和生命周期错误；其任务、报告及复核记录为 AI 辅助软件维护的验证流程提供了具体证据。"),
    ("2026-09-24", "-", "Between the Commits: Process, Error, and Claim Reliability in a Wholly AI-Authored Codebase",
     "Trinity College Dublin",
     "论文", "学界", ["构造方式"],
     ["empirical-study", "observability"],
     "https://arxiv.org/abs/2609.29744",
     None, "分析一个由 Claude 编写的约 2.1 万行 Python 工具的完整开发历史，包括 210 次提交、25 个会话与 678 条用户指令；通过代码来源追踪和会话记录，统计开发触发因素、测试发现的错误及交互陈述的准确性，数据集已公开。",
     "论文将代码块、提交和会话中的用户指令及智能体自我修正相连，提供仅查看最终提交无法取得的编码错误与陈述核查证据；它直接呈现 AI 主导代码开发时的过程与验证问题。"),
    ("2026-09-24", "2026-09-25", "Orchestrating AI-Assisted Code Remediation: Socio-Technical Bottlenecks in a Large Industrial Repository",
     "Ericsson AB; Lund University; Mälardalen University; Carleton University",
     "论文", "产学合作", ["构造方式", "商业与组织"],
     ["empirical-study", "orchestration"],
     "https://arxiv.org/abs/2609.29172",
     None, "报告在大型工业 C++ 仓库中开展的 15 天单案例研究，结合 Gerrit 元数据、开发者日记和团队沟通记录，分析 AI 辅助批量修复对按提交构建的 CI、代码评审和团队协调的影响；原始数据因敏感性未公开。",
     "论文记录按文件提交使 CI 和评审队列承压后，改用目录批处理、限制单次改动规模和主动协调评审的过程；它提供 AI 降低编辑成本后开发流水线及团队分工如何调整的现场证据。"),
    ("2026-09-24", "-", "On the Impact of Requirement Smells in LLM-Based Code Generation",
     "fortiss GmbH; Netlight Consulting; Technical University of Munich; Chalmers University of Technology; Trinity College Dublin; University of Duisburg-Essen; Blekinge Institute of Technology",
     "论文", "产学合作", ["构造方式"],
     ["empirical-study", "benchmark"],
     "https://arxiv.org/abs/2609.29208",
     None, "在四个应用的需求与系统测试数据上，逐步注入语义、句法和词汇层面的需求缺陷，比较两种模型生成代码的测试结果；论文报告缺陷密度与功能正确性的关系，并公开代码、提示词、数据及复现实验包。",
     "研究将软件需求直接作为生成代码的输入，并用对应系统测试检验不同需求缺陷下的实现；其受控实验说明 AI 辅助开发中需求表述与代码验证如何衔接。"),
    ("2026-09-10", "-", "Introducing the Agents API",
     "OpenAI",
     "文章", "厂商", ["构造方式", "运行与问责"],
     ["sandbox", "orchestration", "context-engineering"],
     "https://openai.com/index/introducing-the-agents-api/",
     None, "介绍通过 API 创建由 Codex harness 管理的云端智能体会话，指定模型、工具、子智能体及执行环境；文中说明托管或自有沙箱、长会话上下文压缩、按需工具检索和并行工具调用。",
     "原文给出会话创建示例，并将智能体编排层与可选执行沙箱分开，说明长任务状态、工具发现和子智能体如何由托管运行时提供；这对应 AI 软件的构造架构与运行边界。"),
    ("2026-09-15", "-", "Agent Substrate brings high-density, scalable, trusted infrastructure to GKE",
     "Google Cloud",
     "文章", "厂商", ["构造方式", "安全与攻防"],
     ["sandbox", "orchestration"],
     "https://cloud.google.com/blog/products/containers-kubernetes/agent-substrate-available-on-gke",
     None, "介绍 Agent Substrate 的智能体沙箱运行架构：以微虚拟机或 gVisor 隔离执行环境，通过独立控制面与预热工作节点调度，并以快照暂停、恢复空闲会话；配套核心实现和架构文档已公开。",
     "原文具体说明智能体执行不可信代码时的内核与网络隔离、凭据注入，以及暂停恢复如何从 Kubernetes 节点管理中分离；这些机制对应 AI 开发运行环境的构造方式和安全边界。"),
    ("2026-09-27", "-", "Building an Agentic Software Factory",
     "Zach Rattner",
     "文章", "个人", ["构造方式", "运行与问责"],
     ["skills", "orchestration", "authorization"],
     "https://zachrattner.com/resources/building-an-agentic-software-factory",
     None, "介绍将现有开发流程转为编码 Agent 工作流的方法：把团队约定写入仓库规则和技能，将可重复步骤脚本化，以测试、日志和截图检查结果，并由人审查发布；文中给出仓库结构与发布检查报告示例。",
     "作者以 Yembo 的开发流程为背景，逐步说明技能拆分、命令权限清单、任务隔离及带证据的发布检查如何接入工程流水线；这些具体实践对应 AI 参与软件构造与人类发布责任的安排。"),
    ("2026-09-24", "-", "NEUROTESTGEN: Neuro-Symbolic Guided Test Generation with Large Language Models",
     "York University",
     "论文", "学界", ["构造方式"],
     ["empirical-study", "benchmark"],
     "https://arxiv.org/abs/2609.30178",
     None, "提出针对目标代码行或分支的测试生成方法：用符号执行和 Z3 求解数值路径条件，用模型处理对象相关路径，再通过编译、执行和覆盖率反馈迭代生成测试；论文在 Defects4J 的 14 个项目上报告覆盖率与通过率。",
     "论文给出从未覆盖路径提取约束、生成可执行测试并以覆盖率反馈修正的具体流程，同时列出项目、基线和消融实验；这些可核对的工程方法与数据对应 AI 参与软件测试构造。"),
    ("2026-09-24", "-", "Scan me, Scan me not: Anthropic Built A Skill Scanner. We let Claude bypass it in 7 minutes.",
     "AIR Security",
     "文章", "厂商", ["安全与攻防"],
     ["skills"],
     "https://www.air.security/blog-posts/anthropic-scanner",
     None, "记录研究团队向技能扫描器提交恶意技能的测试，展示外部依赖网址仿冒和二进制隐藏行为两个案例，并说明扫描器返回的判定。",
     "原文以具体技能文件及扫描判定说明所测案例中安装前静态审查未识别外部资源与隐藏行为，直接涉及编码 Agent 技能供应链的安全检查方式。"),
    ("2026-09-17", "-", "Plugin4Shell - Zero Click RCE Vulnerability found in top 4 most popular coding agents, millions of agents affected",
     "AIR Security",
     "文章", "厂商", ["安全与攻防", "构造方式"],
     ["plugins"],
     "https://www.air.security/blog-posts/plugin4shell",
     None, "披露编码 Agent 安装插件时的 Git 提交固定校验问题：恶意仓库可让同名分支或 FETCH_HEAD 分支覆盖指定提交的解析结果；文章给出两种触发路径及安装后核对实际 HEAD 的修复检查。",
     "原文列出插件仓库控制、后台更新、Git 引用解析和缺失的提交核对如何组成攻击链，并给出客户端校验条件；它具体呈现 AI 开发工具的插件分发与执行安全边界。"),
    ("2026-09-24", "-", "Plan mode is dead",
     "Ayman Nadeem",
     "文章", "个人", ["界面与接入", "构造方式"],
     ["tool-interface"],
     "https://www.aymannadeem.com/artificial/intelligence,/developer/tools/2026/09/24/plan-mode-is-dead.html",
     None, "作者回顾 Nuanced 将聊天中的决策整理为持久计划，再进入实现与审查的工作流；介绍 Spec Tour 和计划／构建双模式，记录早期用户对长规格文档的反馈及自己对线性流程的反思。",
     "作者以亲自开发的编码应用为例，具体说明持久计划、规格文档导览和模式切换的设计与使用问题；这些界面与流程安排对应 AI 开发工具的交互和软件构造方式。"),
    ("2026-09-28", "-", "How we found 24 Android vulnerabilities using our open source AI security agent",
     "GitHub Security Lab",
     "文章", "厂商", ["构造方式", "安全与攻防"],
     ["orchestration"],
     "https://github.blog/security/how-we-found-24-android-vulnerabilities-using-our-open-source-ai-security-agent/",
     None, "介绍面向 Android 应用的智能体审计任务流：先区分移动端入口，再按入口类型检查指定漏洞类别，并用多次运行及人工复核处理发现；原文给出运行命令、公开任务流和两个已披露漏洞的代码分析。",
     "作者公开了移动端入口识别与漏洞类别检查的任务流改动，并以 OsmAnd 和 Wikipedia Android 的具体代码路径展示审计结果；这些可检查的步骤为已收录的模糊测试流程之外，增加了 AI 参与移动应用安全审计的实践。"),
    ("2026-09-25", "-", "Compact Documentation for Coding Agents: A Benchmark, an Optimizer, and Why It Does Not Transfer",
     "Daffodil International University; University of Hawai‘i at Mānoa",
     "论文", "学界", ["构造方式"],
     ["context-engineering", "benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.31587",
     None, "提出以原始测试检验自然语言代码描述的回译基准，并用其优化描述提示词；随后在两个模型家族、十个代码仓的议题修复任务中比较压缩文档、检索上下文与仅给议题的条件，报告源码可见时文档未提高修复结果。代码、数据和运行记录由作者公开。",
     "论文将编码 Agent 的文档上下文转为可执行测试判据，并用源码可见与不可见条件检验其对议题修复的作用边界；公开的基准、脚本和运行记录为开发过程中的上下文设计提供了可核查的实证证据。"),
    ("2026-09-25", "-", "MetaPermit: Scalable and Auditable Access Control for AI Agents via LLM-Inferred Meta-Attributes",
     "Paderborn University; Huawei Hilbert Research Center (Dresden); Technical University of Munich; Huawei Technologies Ltd.; Shanghai Jiao Tong University",
     "论文", "产学合作", ["安全与攻防", "运行与问责"],
     ["authorization", "empirical-study"],
     "https://arxiv.org/abs/2609.31039",
     None, "提出工具调用授权框架：模型从用户意图、执行上下文和拟议调用推断元属性，固定策略据此允许或拒绝；论文在 AgentDojo 与 AgentDyn 的七组任务及五类注入方式上比较授权一致性、任务完成和攻击结果，并讨论属性推断错误的限制。",
     "论文给出属性推断、策略判定与执行闸门的分层机制及逐调用审计依据，并用公开基准考察间接提示注入下的授权决策；它对应智能体工具使用时的安全控制和运行问责。"),
    ("2026-09-28", "-", "NVIDIA Open Agent Safety Platform: A Reference for Continuous In-Silicon Agent Monitoring",
     "NVIDIA",
     "文章", "厂商", ["安全与攻防", "运行与问责"],
     ["sandbox", "authorization", "observability"],
     "https://developer.nvidia.com/blog/nvidia-open-agent-safety-platform-a-reference-for-continuous-in-silicon-agent-monitoring/",
     None, "介绍由 OpenShell 智能体沙箱与 BlueField-4 上的 Sentry 组成的分层安全参考架构：运行时按文件、网络、进程和凭据策略限制访问，独立硬件层关联智能体交互、策略决策与工具访问记录。",
     "原文明确划分应用、运行时和基础设施三层，并说明策略验证、带外监测与模型访问路径上的控制点；配套 OpenShell 原仓公开了沙箱及策略实现，呈现智能体运行安全和审计架构的具体变化。"),
    ("2026-09-27", "-", "Identical Runs, Different Results: Benchmarking AI Coding Agents on Open-Weight Models",
     "Central European University; Epoch",
     "论文", "产学合作", ["构造方式", "运行与问责"],
     ["benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.33812",
     None, "在同一机器学习代码改进任务中执行 584 次编码 Agent 运行，比较六种 Agent 与开放权重模型的配对、同配置重复结果、任务规则违规、跨年份测试和调用成本；作者公开每次运行的数据、产出程序及分析脚本。",
     "论文用固定任务和重复运行区分配对差异与随机波动，并对高分程序逐项审查数据使用规则；配套仓可追溯分数、违规判定和成本计算，为 AI 开发工具的评测及交付检查增加实证证据。"),
    ("2026-09-26", "-", "Hearsay: Can an Auditor Trust the Record a Deployed Agent Harness Writes?",
     "Nanyang Technological University; National University of Singapore; Case Western Reserve University",
     "论文", "学界", ["运行与问责", "安全与攻防"],
     ["observability", "empirical-study"],
     "https://arxiv.org/abs/2609.32495",
     None, "研究编码智能体运行记录的审计证据：检查 16 个框架，在五种 harness 的 14 项任务上比较原生记录与外部追加日志，并对遗漏、改写和伪造记录进行盲审及机械核对。",
     "论文给出独立于 harness 的模型交互日志、双向对账查询和注入篡改的测试设计，具体检验运行记录能否支持事后归责；这些方法对应智能体运行的可观测性与审计边界。"),
    ("2026-09-26", "-", "Beyond the Model: Demystifying Harness Effects in Software Engineering Agents",
     "Nanjing University of Science and Technology; Technical University of Munich; Nanjing University",
     "论文", "学界", ["构造方式"],
     ["orchestration", "benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.32459",
     None, "在三个软件工程基准上比较 mini-SWE-agent 与 OpenCode 和十个模型，并以模块化 NanoHarness 分别测试工具注册、上下文压缩、显式规划、子智能体与延迟加载技能对任务结果和执行轨迹的影响。",
     "论文把编码 Agent 的 harness 组件作为受控变量，分离模型、任务类型与工具和协作设计的作用；其跨基准实验为开发工具的构造方式提供了具体的组件级证据。"),
    ("2026-09-25", "-", "Methodological Harness in Agentic Software Engineering: An Empirical Study on Mining Software Repositories",
     "Universidad Politécnica de Madrid",
     "论文", "学界", ["构造方式", "运行与问责"],
     ["skills", "context-engineering", "empirical-study"],
     "https://arxiv.org/abs/2609.32014",
     None, "从 AIDev 数据集中分层抽取并分析 5,435 个有智能体活动的代码仓，检测规则文件、可执行规格、决策记录等工程机制的采用情况；另对 150 个仓库的规则文件进行人工编码。作者公开检测脚本、编码规则和标签。",
     "论文将智能体工程流程中的上下文、规格、接受证据等机制映射为可检测仓库产物，并公开采样及人工复核方法；它为 AI 参与软件构造和团队治理的实际采用范围提供可检查的测量。"),
    ("2026-09-29", "-", "WitnessGym: Benchmarking Coding Agents on the Construction of Bug Witnesses",
     "University of California, San Diego; Purdue University; National University of Singapore",
     "论文", "学界", ["构造方式", "安全与攻防"],
     ["benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.36635",
     None, "提出以缺陷注入构造编码 Agent 缺陷验证任务的方法：在真实 Java 项目的测试可达路径植入缺陷，用构造阶段的可执行见证保留有效案例，再评估 Agent 能否独立生成触发故障的输入和测试程序；论文报告 1,300 个案例及四种 Agent 框架的实验。",
     "论文将安全审计发现的验证要求转为可执行的缺陷见证，并公开构造工具、适配器、测试及案例数据；这些可核查的工程材料呈现 AI 参与缺陷复现与测试时的验证机制。"),
    ("2026-09-29", "-", "Can Agents Design Libraries for Agents?",
     "University of Wisconsin–Madison; Massachusetts Institute of Technology; Snorkel AI; Stanford University",
     "论文", "产学合作", ["构造方式"],
     ["benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.36730",
     None, "提出两阶段 LibraryDesignBench：设计 Agent 根据功能规格实现库，再由三个使用方 Agent 借助该库完成程序任务，以正确性和代码简洁度评分；实验覆盖四种语言、15 项库设计任务和 242 个经专家验证的编程问题，配套仓公开运行框架与任务配置。",
     "论文将 AI 编写的库交给后续 Agent 实际使用，并与无库及现有库条件比较，检验接口设计对后续开发的影响；公开的任务、评分规则和运行代码为 AI 参与软件架构构造提供了可检查的证据。"),
    ("2026-10-01", "-", "Data Agent Kit is now GA: Bring Google Data Cloud to any coding agent",
     "Google Cloud",
     "文章", "厂商", ["界面与接入", "构造方式", "运行与问责"],
     ["MCP", "skills", "authorization"],
     "https://cloud.google.com/blog/topics/developers-practitioners/data-agent-kit-is-now-ga-bring-google-data-cloud-to-any-coding-agent/",
     None, "介绍 Data Agent Kit 将编码 Agent 接入 Google Cloud 数据产品的工作流：MCP 工具提供目录、查询、任务日志和资源操作，技能指导图结构、表结构及数据管道构建；文中说明 IDE 上下文传递、图关系创建前的人工批准和 IAM 权限边界，配套插件与技能仓库公开。",
     "原文给出 Agent 从可信表目录检索、生成并核查 BigQuery 图关系、编排 dbt/Dataform 与 Airflow 流水线以及审查失败任务的具体步骤；公开插件和技能实现使数据工程工作流中的界面接入、构造和权限安排可检查。"),
    ("2026-10-01", "-", "Dynamic workflows in Copilot CLI and the Copilot app",
     "GitHub",
     "文章", "厂商", ["构造方式", "运行与问责"],
     ["orchestration", "authorization"],
     "https://github.blog/changelog/2026-10-01-dynamic-workflows-in-copilot-cli-and-the-copilot-app/",
     None, "介绍 Copilot 动态工作流：以扩展中的程序定义自动步骤、智能体参与时机与结果传递，支持顺序或并行执行、结构化输出、人工检查点和暂停恢复；官方文档另列出子智能体权限继承及运行限额。",
     "原文将开发任务中的多智能体协作固定为可复用的代码流程，并给出发布检查、代码审查等实例；工作流阶段、人工复核与权限规则对应 AI 参与软件构造及运行治理的具体机制。"),
    ("2026-10-01", "-", "GitHub Copilot can now interact with desktop apps with computer use",
     "GitHub",
     "文章", "厂商", ["界面与接入", "安全与攻防"],
     ["computer-use", "authorization"],
     "https://github.blog/changelog/2026-10-01-github-copilot-can-now-interact-with-desktop-apps/",
     None, "介绍 Copilot CLI 与桌面应用公开预览的计算机操作能力：通过辅助功能树或截图读取窗口，执行点击、输入、滚动和跨应用操作；官方文档说明默认关闭、逐应用授权、企业禁用设置及 macOS 系统权限。",
     "原文与配套文档给出智能体访问无 API 桌面软件的操作通道及应用授权边界，呈现 AI 接入现有软件界面的新方式和相应权限控制。"),
    ("2026-09-30", "-", "Towards Efficient HPC Systems for Agents: Challenges and Opportunities",
     "Harvard University; Harvard FAS Research Computing",
     "论文", "学界", ["构造方式", "运行与问责"],
     ["empirical-study", "observability"],
     "https://arxiv.org/abs/2609.38723",
     None, "分析哈佛 FASRC 集群 2026 年 7 月 7 日至 8 月 1 日的调度日志及登录节点进程采样，按智能体进程后代区分操作来源，统计作业提交、资源消耗、命令频率与重试行为，并讨论调度、存储、记忆和安全方面的系统接口。",
     "论文用真实集群遥测记录编码智能体如何改变作业提交和文件操作负载，并指出现有调度及共享存储接口的压力；其测量方法和数据对应 AI 开发工具运行环境及治理方式的变化。"),
    ("2026-09-29", "2026-10-01", "Zero2Repo: Can Coding Agents Build Repositories from Scratch?",
     "Gradient Data; McGill University; Carnegie Mellon University; University of Southern California; Queen’s University; MIT; University College London; University of California, San Diego; independent researchers",
     "论文", "产学合作", ["构造方式"],
     ["benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.38269",
     None, "提出从产品需求和接口契约出发生成完整代码仓的评测：用固定版本开源项目制作规格、可复现环境和隐藏验收测试，在隔离容器中评估智能体提交；论文报告首批 11 项、四种语言任务，配套仓公开任务与运行工具。",
     "原文要求智能体自行完成目录、依赖、构建和实现，并在提交后由独立容器执行隐藏测试；这与已有的局部修复评测及库接口设计评测相比，增加了完整软件仓库交付的可检查任务和验收流程。"),
    ("2026-09-29", "-", "E2E-SWE: Benchmarking LLMs on Building Working Codebases from Scratch",
     "Meta Superintelligence Labs",
     "论文", "厂商", ["构造方式"],
     ["benchmark", "empirical-study"],
     "https://arxiv.org/abs/2609.38335",
     None, "提出覆盖 11 种语言、186 项完整代码仓生成任务的 E2E-SWE：智能体从自然语言规格和空工作区创建可安装项目，由独立容器中的隐藏测试验收；任务由工程师与模型共同构造，并通过静态检查和实际运行迭代校验，原仓公开任务与适配器。",
     "论文把从零构建软件的评测扩展到多语言任务，并公开逐任务规格、测试及运行适配器；相较同日的 Zero2Repo，其工程师参与构造及基于实际运行修订任务的流程提供了另一套可核查的任务生成与验收证据。"),
    ("2026-10-01", "-", "Finding the Right Fit: Model-Harness Interactions across Agent Tasks",
     "Nanyang Technological University",
     "论文", "学界", ["构造方式"],
     ["orchestration", "benchmark", "empirical-study"],
     "https://arxiv.org/abs/2610.00917",
     None, "在 TUA-Bench、ALE-CLI 与 Terminal-Bench 4 上比较五种模型与四种可配置 harness，以及两组厂商原生配对，共 66 种配置；论文分别报告任务分数、成本和匹配轨迹分析，作者公开适配器、评测代码及 6,204 条计分轨迹。",
     "原文将模型、执行框架和任务组合一同作为评测单位，并公开跨三种任务集的配置、成本核算与运行轨迹；相较目录已有的 harness 组件消融与单任务重复运行研究，增加了跨模型和框架配对变化的可检查证据。"),
    ("2026-09-17", "-", "Localizing Post-Wire Semantic Changes in MCP Agent Frameworks",
     "Aditi Patodiya (independent researcher)",
     "论文", "个人", ["协议与生态", "构造方式"],
     ["MCP", "tool-interface", "empirical-study"],
     "https://arxiv.org/abs/2610.00182",
     None, "以 18 个设计夹具对四种固定版本的 Python Agent 集成做差分测试，追踪 MCP 工具结果在应用接口和模型输入中的结构化值、错误状态及富内容表示；论文报告 13 组独立的夹具与任务差异，并提供捕获记录和确定性分析复现包。",
     "原文把 MCP 消息到 Agent 框架下游接口的语义保持转为可执行的消费者契约，并区分运行失败、未观察到结果及字段变化；公开的测试夹具、记录和重建程序为协议接入后的兼容性验证提供具体证据。"),
    ("2026-10-02", "-", "My Coding Agents Moved Off My Laptop and Onto a Remote Server",
     "Rob Bell",
     "文章", "个人", ["构造方式", "安全与攻防", "运行与问责"],
     ["sandbox", "authorization", "orchestration"],
     "https://spin.atomicobject.com/coding-agents-remote-server/",
     None, "记录作者将长期运行的编码 Agent 迁至远程服务器的工程实践：按客户划分虚拟机，在各虚拟机内用 Git worktree 隔离并行任务；通过私有网络、主机防火墙和逐机凭据限制跨项目访问，并用终端会话记录支持断线及重启后恢复。",
     "原文给出虚拟机克隆命令、网络准入测试与出站防火墙规则，并说明凭据分离、可中断的配置流程及项目结束时的撤销步骤；这些具体配置呈现编码 Agent 持续运行和多客户并行开发时的环境构造与权限边界。"),
    ("2026-10-03", "-", "Moving an engineering team to agent-driven delivery: six months of real numbers",
     "Vinod Kurien Alex",
     "文章", "个人", ["构造方式", "运行与问责", "商业与组织"],
     ["orchestration", "skills", "empirical-study"],
     "https://www.techlifeadventures.com/post/case-study-ai-native-engineering",
     None, "作者记录在多代码仓使用编码 Agent 的六个月实践，说明任务路由、书面交接、团队共享的测试 Agent 包和定时检查；以 Git、PR 与会话记录比较个人工作量，并列出分割日期、计数规则和同期角色变化等限制。",
     "原文给出定时 Agent 误发内部简报、路由会话过长和虚构工单号进入发布记录的处置步骤，并说明团队如何修改发布权限、会话交接与事实核查规则；这些一手实践对应开发流程和运行问责的具体调整。"),
    ("2026-10-02", "-", "Build anything: Supabase from code, and an MCP server for your app",
     "Supabase (Wen Bo Xie; Lakshan Perera; Julien Goux; Andrew Valleteau; Rand Arete; Katerina Skroumpelou)",
     "文章", "厂商", ["构造方式", "界面与接入", "安全与攻防"],
     ["MCP", "tool-interface", "authorization"],
     "https://supabase.com/blog/select-2026-build-anything",
     None, "介绍面向编码 Agent 的后端开发流程：把数据库 schema 和项目配置写入代码仓，由差分工具生成迁移，并为每个工作目录启动独立本地实例；另说明应用自有 MCP 服务如何沿用用户登录及行级访问策略。",
     "原文列出声明式 schema、配置回拉、本地实例开关和 MCP 服务部署命令，具体呈现 Agent 在代码仓内修改与验证后端的方式，以及应用向用户 Agent 开放能力时的授权边界。"),
    ("2026-09-30", "-", "Understanding and Mitigating Library-Related Issues in LLM-Generated Code",
     "University of Gabes; University of Calgary; National School of Engineering, Gabes",
     "论文", "学界", ["构造方式"],
     ["context-engineering", "empirical-study"],
     "https://arxiv.org/abs/2610.00622",
     None, "研究生成代码中的外部库使用错误：人工分析 100 份代码并归类导入问题，构建依赖分析、文档检索、代码生成与编译验证循环，在 300 项 Python 任务上比较五种模型；作者仓库公开任务数据与实现。",
     "论文把动态库文档和实际编译反馈接入编码 Agent 的生成循环，并公开 300 项任务与各模块实现；相较目录已有的文档上下文评测，它针对库版本与导入错误给出可检查的开发流程及实验对象。"),
    ("2026-09-30", "-", "ASAD: Adaptive Software Agents for Debugging",
     "University of Gabes; National School of Engineering, Gabes",
     "论文", "学界", ["构造方式"],
     ["orchestration", "benchmark", "empirical-study"],
     "https://arxiv.org/abs/2610.00629",
     None, "提出按缺陷复杂度选择单 Agent 修复或专门分工的多 Agent 调试流程，论文在 DebugBench、Defects4J 与 CodeFlaws 上比较修复和资源使用；作者仓库公开路由实现及 DebugBench、CodeFlaws 的部分运行结果。",
     "原文把缺陷分析结果用于决定调试 Agent 的数量、角色和执行顺序，并给出固定协作策略的对照；公开代码及两组基准运行记录使这种按任务调整开发工作流的机制可检查。"),
    ("2026-10-01", "-", "Understanding Issues, Causes and Solutions in Open-Source LLM-based Multi-Agent Systems",
     "Wuhan University; Central China Normal University; University of Oulu",
     "论文", "学界", ["构造方式", "运行与问责"],
     ["orchestration", "empirical-study"],
     "https://arxiv.org/abs/2610.00905",
     None, "从 21 个开源多智能体项目收集 22,848 条已关闭问题，经过自动与人工筛选得到 944 条相关问题，再编码问题类别、成因和解决方式；作者仓库公开原始问题、试标及最终编码数据。",
     "论文直接测量多智能体软件中的编排执行、工具集成和记忆状态问题，并公开从问题筛选到分类的记录；这些实际缺陷证据补充目录已有的 Agent 框架设计与基准评测。"),
]

# 无摘要条目的可审计原因；来源受限时不根据标题补写。
SUMMARY_GAPS = {
    "https://www.iso.org/standard/42001":
        "ISO 页面版权条款禁止将受版权保护内容用于 AI 生成回答。",
    "https://my.idc.com/getdoc.jsp?containerId=US54377825":
        "IDC 报告全文需要登录，当前只能看到落地页，无法据原文核实摘要。",
}

# 原件不随仓分发的，写明理由。其余默认「可用 fetch.sh 取回本地」。
NO_REDISTRIBUTION = {
    "standard-tc260-agent-dev-security-guide":
        "文件声明「未经秘书处书面授权，不得以任何方式抄袭、翻译任何部分」",
    "analyst-idc-landing": "正文在付费墙后，此处仅落地页元数据",
}
ARXIV_NOTE = ("arXiv 默认许可为 nonexclusive-distrib/1.0——作者授权 arXiv 分发，"
              "**未授权第三方转载**，故本仓不放 PDF 副本")
