# -*- coding: utf-8 -*-
"""条目清单——本仓唯一的数据源，README 与 index.tsv 都由它生成。

每条七个字段：发布日期、标题、出品方、类型标签、主题标签、出处地址、抓取到的原件 sha256。
**不写评价，不写解读**——本仓只做收集、打标签、按发布时间排序。

主题标签用六个分区，判据是「什么在被重构」：
  界面与接入 ｜ 应用内部 ｜ 构造方式 ｜ 运行与治理 ｜ 协议与生态 ｜ 商业与组织
类型标签：论文 ｜ 厂商 ｜ 标准 ｜ 分析 ｜ 投资 ｜ 社区
"""

# 发布日期, 标题, 出品方, 类型, [主题标签], 出处, 原件键名（对应 fetched.tsv 的名称列）
ITEMS = [
    ("2026-09-16", "Characterizing Network Centralization and Observability in the Remote MCP Ecosystem",
     "卡尔加里大学", "论文", ["协议与生态", "运行与治理"],
     "https://arxiv.org/abs/2609.19100", "academic-2609.19100-remote-mcp-centralization"),
    ("2026-09-15", "Salesforce Koa: An Enterprise Language Model for Agentic Tool Use",
     "Salesforce", "论文", ["构造方式"],
     "https://arxiv.org/abs/2609.15066", "academic-2609.15066-salesforce-koa"),
    ("2026-09-14", "Authorization Architectures for Tool-Using AI Agents",
     "（见原文）", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2609.15906", "academic-2609.15906-authorization-architectures"),
    ("2026-09-14", "When Tool Calls Succeed but Workflows Fail: Anomalies at the Agent-Tool Boundary",
     "（见原文）", "论文", ["构造方式"],
     "https://arxiv.org/abs/2609.15397", "academic-2609.15397-tool-calls-succeed-workflows-fail"),
    ("2026-09-13", "A Two-Dimensional Study of the Model Context Protocol: Publication and Adoption",
     "卢森堡科技研究院、卢森堡大学", "论文", ["协议与生态"],
     "https://arxiv.org/abs/2609.14721", "academic-2609.14721-mcp-publication-adoption"),
    ("2026-09-13", "The Stochastic Deputy: Structural Tenant Isolation for Tool-Using LLM Agents",
     "（见原文）", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2609.14780", "academic-2609.14780-stochastic-deputy-tenant-isolation"),
    ("2026-09-12", "Same Name, Different Server: A Security Census of Silent Drift in MCP",
     "（见原文）", "论文", ["协议与生态", "运行与治理"],
     "https://arxiv.org/abs/2609.14119", "academic-2609.14119-same-name-different-server"),
    ("2026-09-10", "Is Bash All You Need? An Empirical Study of Tool Interfaces for Enterprise Digital Worker Agents",
     "Microsoft、卡内基梅隆大学", "论文", ["构造方式", "界面与接入"],
     "https://arxiv.org/abs/2609.11999", "academic-2609.11999-is-bash-all-you-need"),
    ("2026-09-05", "Intent Drift at SME Scale: Deployment Practice, Not Model Capability, Determines Agentic Compliance",
     "香港科技大学", "论文", ["运行与治理", "应用内部"],
     "https://arxiv.org/abs/2609.05975", "academic-2609.05975-intent-drift-sme"),
    ("2026-08-31", "Delegation Without Trust: An Empirical Gap Analysis of Identity, Authorization, and Runtime",
     "（见原文）", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2609.00267", "academic-2609.00267-delegation-without-trust"),
    ("2026-08-25", "Hybrid Semantic Tool Discovery for Enterprise MCP Gateway: Architecture and Implementation",
     "（见原文）", "论文", ["协议与生态", "构造方式"],
     "https://arxiv.org/abs/2608.23992", "academic-2608.23992-semantic-tool-discovery"),
    ("2026-08-25", "MCPVerse: An Expansive, Real-World Benchmark for Agentic Tool Use",
     "（见原文）", "论文", ["构造方式"],
     "https://arxiv.org/abs/2508.16260", "academic-2508.16260-mcpverse"),
    ("2026-08-22", "From SQL Generation to Tool Selection: A Domain-Oriented Pattern for MCP Servers",
     "（见原文）", "论文", ["界面与接入", "构造方式"],
     "https://arxiv.org/abs/2608.22063", "academic-2608.22063-domain-oriented-tooling"),
    ("2026-08-19", "Expanding Headless 360: Turning Enterprise Applications into Enterprise Capabilities",
     "Salesforce", "厂商", ["界面与接入"],
     "https://www.salesforce.com/news/stories/expanding-headless-360-enterprise-capabilities/",
     "vendor-salesforce-headless-360"),
    ("2026-07-28", "Model Context Protocol Specification (version 2026-07-28)",
     "Model Context Protocol", "标准", ["协议与生态"],
     "https://modelcontextprotocol.io/specification/latest", "standard-mcp-spec-index"),
    ("2026-06-30", "Benchmarking the Benchmarks: A Validity Audit of Tool-Calling Evaluation",
     "CoreThink AI、斯坦福大学", "论文", ["构造方式"],
     "https://arxiv.org/abs/2607.02577", "academic-2607.02577-benchmark-validity-audit"),
    ("2026-06-08", "Understanding How Enterprises Adopt the Model Context Protocol for LLM-Driven Software Engineering",
     "香港城市大学、香港都会大学", "论文", ["协议与生态", "构造方式"],
     "https://arxiv.org/abs/2606.09182", "academic-2606.09182-enterprise-mcp-adoption"),
    ("2026-05-28", "Awesome Context Engineering（配套仓）",
     "中科院计算所等", "社区", ["应用内部", "构造方式"],
     "https://github.com/Meirtz/Awesome-Context-Engineering", "community-context-engineering-readme"),
    ("2026-05-13", "ServiceNow opens its full system of action to every AI Agent in the enterprise（Action Fabric）",
     "ServiceNow", "厂商", ["界面与接入", "运行与治理"],
     "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-opens-its-full-system-of-action-to-every-AI-Agent-in-the-enterprise/default.aspx",
     "vendor-servicenow-action-fabric"),
    ("2026-05-02", "The Buy-or-Build Decision, Revisited: How Agentic AI Changes the Economics of Enterprise Software",
     "斯图加特媒体大学", "论文", ["商业与组织"],
     "https://arxiv.org/abs/2604.26482", "academic-2604.26482-buy-or-build"),
    ("2026-04-26", "Infrastructure for the Agentic Web: Gap Analysis and Architecture from the Agentverse Platform",
     "OpenHub Research", "论文", ["协议与生态"],
     "https://arxiv.org/abs/2606.20570", "academic-2606.20570-agentic-web-infra"),
    ("2026-04", "SAP API Policy v.4.2026a",
     "SAP", "厂商", ["界面与接入", "协议与生态"],
     "https://help.sap.com/doc/sap-api-policy/latest/en-US/API_Policy_latest.pdf", "vendor-sap-api-policy"),
    ("2026-03-26", "From Logic Monopoly to Social Contract（工作论文，未经同行评议）",
     "NetX Foundation", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2603.25100", "academic-2603.25100-logic-monopoly"),
    ("2026-03-02", "Good news: AI Will Eat Application Software",
     "a16z", "投资", ["商业与组织"],
     "https://a16z.com/good-news-ai-will-eat-application-software/", None),
    ("2026-03", "AI Isn't Going to \"Eat\" Software: Agentic AI Needs the Authoritative Data and Rules Inside Enterprise Apps",
     "IDC", "分析", ["商业与组织"],
     "https://my.idc.com/getdoc.jsp?containerId=US54377825", "analyst-idc-landing"),
    ("2026-02-24", "The Headless Firm: How AI Reshapes Enterprise Boundaries",
     "Mantix（作者自陈利益冲突）", "论文", ["界面与接入", "商业与组织"],
     "https://arxiv.org/abs/2602.21401", "academic-2602.21401-headless-firm"),
    ("2026-01-01", "Going Headless? On the Boundaries of Vertical AI Firms",
     "匹兹堡大学、Ensi.ai", "论文", ["界面与接入", "商业与组织", "运行与治理"],
     "https://arxiv.org/abs/2605.17812", "academic-2605.17812-going-headless"),
    ("2025-12-09", "2025: The State of Generative AI in the Enterprise（495 人问卷）",
     "Menlo Ventures", "投资", ["商业与组织"],
     "https://menlovc.com/perspective/2025-the-state-of-generative-ai-in-the-enterprise/",
     "investor-menlo-state-of-genai"),
    ("2025-12-09", "OWASP Top 10 for Agentic Applications for 2026",
     "OWASP GenAI Security Project", "标准", ["运行与治理"],
     "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/", None),
    ("2025-11-25", "Securing the Model Context Protocol (MCP): Risks, Controls, and Governance",
     "Vanta、MintMCP、Darktrace", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2511.20920", "academic-2511.20920-securing-mcp"),
    ("2025-11-05", "Technology Radar：Model Context Protocol (MCP) 评为 Trial",
     "ThoughtWorks", "分析", ["协议与生态"],
     "https://www.thoughtworks.com/radar/platforms/model-context-protocol-mcp", None),
    ("2025-10-20", "Evolution of AI Agent Registry Solutions: Centralized, Enterprise, and Distributed Approaches",
     "麻省理工、Cisco、克利夫兰州立大学等", "论文", ["协议与生态"],
     "https://arxiv.org/abs/2508.03095", "academic-2508.03095-agent-registries"),
    ("2025-09-11", "Writing effective tools for agents — with agents",
     "Anthropic", "厂商", ["构造方式"],
     "https://www.anthropic.com/engineering/writing-tools-for-agents", "toolcraft-anthropic-writing-tools"),
    ("2025-09-01", "An Economy of AI Agents（美国国家经济研究局手册章节）",
     "约翰霍普金斯大学、麻省理工", "论文", ["商业与组织"],
     "https://arxiv.org/abs/2509.01063", "academic-2509.01063-economy-of-ai-agents"),
    ("2025-07-21", "A Survey of Context Engineering for Large Language Models",
     "中科院计算所、北京大学、清华大学等", "论文", ["应用内部"],
     "https://arxiv.org/abs/2507.13334", "academic-2507.13334-context-engineering-survey"),
    ("2025-05-02", "Enterprise-Grade Security for the Model Context Protocol (MCP)",
     "亚马逊云科技、Intuit", "论文", ["运行与治理"],
     "https://arxiv.org/abs/2504.08623", "academic-2504.08623-enterprise-mcp-security"),
    ("2025-05", "From Glue-Code to Protocols: A Critical Analysis of A2A and MCP Integration",
     "肯尼索州立大学", "论文", ["协议与生态"],
     "https://arxiv.org/abs/2505.03864", "academic-2505.03864-a2a-mcp-integration"),
    # —— 无固定发布日、持续更新的条目，按抓取日期归到当日 ——
    ("2026-09-20", "MCP 官方注册表：设计原则与生态愿景", "Model Context Protocol", "标准",
     ["协议与生态"], "https://github.com/modelcontextprotocol/registry",
     "standard-mcp-registry-design-principles"),
    ("2026-09-20", "A2A Protocol 官网：治理与技术指导委员会", "Linux 基金会", "标准",
     ["协议与生态"], "https://a2a-protocol.org/latest/", "standard-a2a-protocol-home"),
    ("2026-09-20", "Agent Communication Protocol 官网", "（见原文）", "标准",
     ["协议与生态"], "https://agentcommunicationprotocol.dev/", "standard-acp-protocol-home"),
    ("2026-09-20", "Atlassian Remote MCP Server 产品页", "Atlassian", "厂商",
     ["界面与接入", "运行与治理"], "https://www.atlassian.com/platform/remote-mcp-server",
     "vendor-atlassian-remote-mcp"),
    ("2026-09-20", "Agentforce 定价页（按对话计费）", "Salesforce", "厂商",
     ["商业与组织"], "https://www.salesforce.com/agentforce/pricing/",
     "vendor-salesforce-agentforce-pricing"),
    ("2026-09-20", "Fin 定价页（按结果计费）", "Intercom", "厂商",
     ["商业与组织"], "https://www.intercom.com/pricing", "vendor-intercom-fin-pricing"),
    ("2026-09-20", "Function calling 开发者文档", "OpenAI", "厂商",
     ["构造方式"], "https://platform.openai.com/docs/guides/function-calling",
     "toolcraft-openai-function-calling"),
    ("2026-09-20", "AI Risk Management Framework（1.0 修订中）", "美国国家标准与技术研究院", "标准",
     ["运行与治理"], "https://www.nist.gov/itl/ai-risk-management-framework", "standard-nist-ai-rmf"),
    ("2026-09-20", "EU AI Act 实施时间线", "Future of Life Institute（追踪站）", "标准",
     ["运行与治理"], "https://artificialintelligenceact.eu/implementation-timeline/",
     "standard-eu-ai-act-timeline"),
    ("2026-09-20", "The State Of Agentic AI In 2026（公开博客）", "Forrester", "分析",
     ["商业与组织"], "https://www.forrester.com/blogs/the-state-of-agentic-ai-in-2026-companies-are-chasing-few-are-catching/",
     "analyst-forrester-state-of-agentic-ai"),
    ("2026-09-20", "awesome-ai-agent-papers（388 篇 2026 年论文）", "VoltAgent", "社区",
     ["应用内部", "构造方式", "运行与治理"], "https://github.com/VoltAgent/awesome-ai-agent-papers",
     "community-voltagent-agent-papers"),
    ("2026-09-20", "awesome-mcp-security", "Puliczek", "社区",
     ["运行与治理"], "https://github.com/Puliczek/awesome-mcp-security", "community-puliczek-mcp-security"),
    ("2026-09-20", "800+ MCP 服务端安全评分", "getagentseal", "社区",
     ["运行与治理", "协议与生态"], "https://github.com/getagentseal/awesome-mcp-security",
     "community-agentseal-mcp-server-scores"),
    ("2026-09-20", "百炼文档（兼容 OpenAI 接口规范）", "阿里云", "厂商",
     ["构造方式"], "https://help.aliyun.com/zh/model-studio/", "platform-aliyun-bailian"),
    ("2026-09-18", "网络安全标准实践指南——智能体系统开发安全指南（征求意见稿 v1.0-202609）",
     "全国网络安全标准化技术委员会", "标准", ["运行与治理", "界面与接入"],
     "https://www.tc260.org.cn/tc260/tzgg/202609/e5b82ae7aca244d19d36b39575cbb458.shtml",
     "standard-tc260-agent-dev-security-guide"),
]

# 原件不随仓分发的，写明理由。其余默认「可用 fetch.sh 取回本地」。
NO_REDISTRIBUTION = {
    "standard-tc260-agent-dev-security-guide":
        "文件声明「未经秘书处书面授权，不得以任何方式抄袭、翻译任何部分」",
    "analyst-idc-landing": "正文在付费墙后，此处仅落地页元数据",
}
ARXIV_NOTE = ("arXiv 默认许可为 nonexclusive-distrib/1.0——作者授权 arXiv 分发，"
              "**未授权第三方转载**，故本仓不放 PDF 副本")
